[project]
name = "Cadastre-plugin"
authors = [
    { name = "3liz", email = "info@3liz.com" }
]
version = "2.2.6"
requires-python = ">=3.9"
license = "GPL-2.0-only"
license-files = ["LICENSE"]
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering :: GIS",
]

[dependency-groups]
dev = [
    "coverage[toml]",
    {include-group = "tests"},
    {include-group = "lint"},
]
tests = [
    "pytest >= 5.3",
    "pytest-qgis",
    "semver",
]
lint = [
    "ruff",
    "mypy",
    "bandit",
]

[tool.uv.sources]
pytest-qgis = { git = "https://github.com/3liz/pytest-qgis.git" }

[tool.yapt]
plugin_source = "cadastre"


# Ruff configuration
# See https://doc.astral.sh/ruff/configuration

[tool.ruff]
line-length = 110
target-version = "py39"
exclude = [
    ".venv",
    ".local",
    ".test/.local",
    ".cache",
]

[tool.ruff.format]
indent-style = "space"

[tool.ruff.lint]
extend-select = [
    "E", "F", "ANN", "W", "T", "COM", "RUF",
    "C4", "SIM", "TC", "RET",
]
ignore = [
    "ANN002",
    "ANN003",
    "ANN401",
    "COM812", # Conflict with format
    "SIM108", # Use ternary operator
    "RUF067", # module should only contain docstrings and re-exports
    # XXX Fix 
    "E501", # Line too long
]

[tool.ruff.per-file-target-version]
"lizmap_server/context/qjazz.py" = "py312"

[tool.ruff.lint.per-file-ignores]
"tests/*" = [
    "T201",
    "E501",
]
"cadastre/tests/*" = [
    "T201",
]
"cadastre/standalone/export.py" = [
    "T201",
]

[tool.ruff.lint.isort]
#lines-between-types = 1
known-third-party = [
    "qgis",
]

[tool.ruff.lint.flake8-annotations]
ignore-fully-untyped = true
suppress-none-returning = true
suppress-dummy-args = true

#
# Mypy
#
[tool.mypy]
python_version = "3.9"

exclude = [
    "lizmap_server/context/py_qgis_server.py",
    "lizmap_server/context/qjazz.py",
]

[[tool.mypy.overrides]]
module = "lizmap_server.context.qjazz"
follow_imports = "skip"

[[tool.mypy.overrides]]
module = "lizmap_server.context.py_qgis_server"
follow_imports = "skip"

[[tool.mypy.overrides]]
module = [
    "qgis.*",
    "osgeo.*",
    "xmldiff.*",
]
ignore_missing_imports = true

#
# Coverage
#

[tool.coverage.run]
source = ["cadastre"]
branch = true
relative_files = true

[tool.coverage.report]
precision = 2
exclude_lines = [
 "if TYPE_CHECKING",
 '\(Protocol\):$',
]
