-- nomenclature gpdl (parcelle)
INSERT INTO gpdl VALUES ('0','la parcelle n''appartient pas à une pdl');
INSERT INTO gpdl VALUES ('1','la parcelle est référence de pdl (identifie une pdl)');
INSERT INTO gpdl VALUES ('2','la parcelle est composante de pdl mais ne l''identifie pas');
-- nomenclature gnexps (suf)
INSERT INTO gnexps VALUES ('CD', 'Exonération permanente des parts communale et départementale(Bien d''une région situe dans une autre région)');
INSERT INTO gnexps VALUES ('CR', 'Exonération permanente des parts communale et régionale (Bien d''un département situe dans un autre département)');
INSERT INTO gnexps VALUES ('DR', 'Exonération permanente des parts départementale et régionale (Bien d''une commune situe dans une autre commune)');
INSERT INTO gnexps VALUES ('EP', 'Exonération permanente totale');
INSERT INTO gnexps VALUES ('NI', 'Non imposable - Exonération toutes collectivités');
INSERT INTO gnexps VALUES ('RT', 'Exonération des chemins de remembrements association foncière de remembrement');
INSERT INTO gnexps VALUES ('CC', 'exonération des parts TSE et TATFNB pour les biens communaux situés sur le territoire d’une autre commune de la métropole de Lyon');
INSERT INTO gnexps VALUES ('DD', 'exonération des parts communale, intercommunale et TSE pour les biens appartenant à un département situés en dehors de son territoire');
INSERT INTO gnexps VALUES ('GG', 'exonération des parts TSE et TAFNB pour les biens appartenant à un EPCI ou à la métropole de Lyon et situés en dehors de son territoire');
INSERT INTO gnexps VALUES ('GN', 'transfert de propriétés non bâties par l’État aux grands ports maritimes affectés à un service public ou d utilité générale et non productifs de revenus');

-- nomenclature cgrnum (suf)
INSERT INTO cgrnum VALUES ('01', 'Terres');
INSERT INTO cgrnum VALUES ('02', 'Prés');
INSERT INTO cgrnum VALUES ('03', 'Vergers');
INSERT INTO cgrnum VALUES ('04', 'Vignes');
INSERT INTO cgrnum VALUES ('05', 'Bois');
INSERT INTO cgrnum VALUES ('06', 'Landes');
INSERT INTO cgrnum VALUES ('07', 'Carrières');
INSERT INTO cgrnum VALUES ('08', 'Eaux');
INSERT INTO cgrnum VALUES ('09', 'Jardins');
INSERT INTO cgrnum VALUES ('10', 'Terrains à bâtir');
INSERT INTO cgrnum VALUES ('11', 'Terrains d''agrément');
INSERT INTO cgrnum VALUES ('12', 'Chemin de fer');
INSERT INTO cgrnum VALUES ('13', 'Sol');
-- nomenclature dsgrpf (suf)
INSERT INTO dsgrpf VALUES ('AB', 'Terrains à bâtir');
INSERT INTO dsgrpf VALUES ('AG', 'Terrains d’agrément');
INSERT INTO dsgrpf VALUES ('B', 'Bois');
INSERT INTO dsgrpf VALUES ('BF', 'Futaies Feuillues');
INSERT INTO dsgrpf VALUES ('BM', 'Futaies Mixtes');
INSERT INTO dsgrpf VALUES ('BO', 'Oseraies');
INSERT INTO dsgrpf VALUES ('BP', 'Peupleraies');
INSERT INTO dsgrpf VALUES ('BR', 'Futaies résineuses');
INSERT INTO dsgrpf VALUES ('BS', 'Taillis sous Futaies');
INSERT INTO dsgrpf VALUES ('BT', 'Taillis simples');
INSERT INTO dsgrpf VALUES ('CA', 'Carrières');
INSERT INTO dsgrpf VALUES ('CH', 'Chemins de fer, Canaux de Navigation');
INSERT INTO dsgrpf VALUES ('E', 'Eaux');
INSERT INTO dsgrpf VALUES ('J', 'Jardins');
INSERT INTO dsgrpf VALUES ('L', 'Landes');
INSERT INTO dsgrpf VALUES ('LB', 'Landes Boisées');
INSERT INTO dsgrpf VALUES ('P', 'Prés');
INSERT INTO dsgrpf VALUES ('PA', 'Pâtures ou Pâturages');
INSERT INTO dsgrpf VALUES ('PC', 'Pacages ou Pâtis');
INSERT INTO dsgrpf VALUES ('PE', 'Prés d''embouche');
INSERT INTO dsgrpf VALUES ('PH', 'Herbages');
INSERT INTO dsgrpf VALUES ('PP', 'Prés, Pâtures ou Herbages plantes');
INSERT INTO dsgrpf VALUES ('S', 'Sols');
INSERT INTO dsgrpf VALUES ('T', 'Terre');
INSERT INTO dsgrpf VALUES ('TP', 'Terres plantées');
INSERT INTO dsgrpf VALUES ('VE', 'Vergers');
INSERT INTO dsgrpf VALUES ('VI', 'Vignes');
-- nomenclature cnatsp (suf)
INSERT INTO cnatsp VALUES ('ABREU', 'Abreuvoirs');
INSERT INTO cnatsp VALUES ('ABRIC', 'Abricotiers');
INSERT INTO cnatsp VALUES ('ACACI', 'Acacias');
INSERT INTO cnatsp VALUES ('AEROD', 'Aérodromes');
INSERT INTO cnatsp VALUES ('AIRE', 'Aire ou Airial');
INSERT INTO cnatsp VALUES ('ALLEE', 'Allée (no groupe)');
INSERT INTO cnatsp VALUES ('ALLUV', 'Alluvions');
INSERT INTO cnatsp VALUES ('AMAND', 'Amandiers');
INSERT INTO cnatsp VALUES ('ARDOI', 'Ardoiseries');
INSERT INTO cnatsp VALUES ('ARGIL', 'Argilière');
INSERT INTO cnatsp VALUES ('ASPER', 'Aspergeraie');
INSERT INTO cnatsp VALUES ('AULNE', 'Aulnaie');
INSERT INTO cnatsp VALUES ('AVENU', 'Avenue');
INSERT INTO cnatsp VALUES ('BALLA', 'Ballastière');
INSERT INTO cnatsp VALUES ('BAMBO', 'Bambouseraie');
INSERT INTO cnatsp VALUES ('BASS', 'Bassins');
INSERT INTO cnatsp VALUES ('BIEF', 'Bief');
INSERT INTO cnatsp VALUES ('BOUL', 'Boulaie');
INSERT INTO cnatsp VALUES ('BROUS', 'Broussailles ou buissons');
INSERT INTO cnatsp VALUES ('BRUY', 'Bruyères');
INSERT INTO cnatsp VALUES ('BTIGE', 'Verger exploite en basses tiges');
INSERT INTO cnatsp VALUES ('BUIS', 'Buissière');
INSERT INTO cnatsp VALUES ('CAMP', 'Terrain de camping');
INSERT INTO cnatsp VALUES ('CANAL', 'Canal');
INSERT INTO cnatsp VALUES ('CASS', 'Cassis');
INSERT INTO cnatsp VALUES ('CEDRA', 'Cédratiers');
INSERT INTO cnatsp VALUES ('CERCL', 'Cerclières');
INSERT INTO cnatsp VALUES ('CERIS', 'Cerisaie ou cerisiers');
INSERT INTO cnatsp VALUES ('CHASS', 'Terrain de chasse');
INSERT INTO cnatsp VALUES ('CHAT', 'Châtaigneraie');
INSERT INTO cnatsp VALUES ('CHEM', 'Chemin de remembrement');
INSERT INTO cnatsp VALUES ('CHENE', 'Chênes');
INSERT INTO cnatsp VALUES ('CHLIE', 'Chênes-lièges');
INSERT INTO cnatsp VALUES ('CHTRU', 'Chênes truffiers');
INSERT INTO cnatsp VALUES ('CHVER', 'Chênes verts');
INSERT INTO cnatsp VALUES ('CIDRE', 'Cidre');
INSERT INTO cnatsp VALUES ('CITRO', 'Citronniers');
INSERT INTO cnatsp VALUES ('CLAIR', 'Claires');
INSERT INTO cnatsp VALUES ('COING', 'Cognassiers');
INSERT INTO cnatsp VALUES ('COULE', 'Bois de couleur');
INSERT INTO cnatsp VALUES ('CRAY', 'Crayère');
INSERT INTO cnatsp VALUES ('CRESS', 'Cressonnière');
INSERT INTO cnatsp VALUES ('CRYPT', 'Cryptomeria');
INSERT INTO cnatsp VALUES ('DIGUE', 'Digues');
INSERT INTO cnatsp VALUES ('DUNE', 'Dunes');
INSERT INTO cnatsp VALUES ('EAU', 'Pièce d''eau');
INSERT INTO cnatsp VALUES ('ECOLE', 'Ecole');
INSERT INTO cnatsp VALUES ('EPICE', 'Epicéas');
INSERT INTO cnatsp VALUES ('ESPAL', 'Verger exploite en espaliers');
INSERT INTO cnatsp VALUES ('ETANG', 'Etangs');
INSERT INTO cnatsp VALUES ('EUCAL', 'Eucalyptus');
INSERT INTO cnatsp VALUES ('FALAI', 'Falaises');
INSERT INTO cnatsp VALUES ('FAMIL', 'Verger familial');
INSERT INTO cnatsp VALUES ('FER', 'Chemin de fer');
INSERT INTO cnatsp VALUES ('FILAO', 'Filao');
INSERT INTO cnatsp VALUES ('FLOR', 'Jardin floral');
INSERT INTO cnatsp VALUES ('FONT', 'Fontaine');
INSERT INTO cnatsp VALUES ('FOSSE', 'Fosse');
INSERT INTO cnatsp VALUES ('FOUG', 'Fougeraie');
INSERT INTO cnatsp VALUES ('FRAMB', 'Framboisiers');
INSERT INTO cnatsp VALUES ('FRICH', 'Friche');
INSERT INTO cnatsp VALUES ('GAREN', 'Garenne');
INSERT INTO cnatsp VALUES ('GENET', 'Genets');
INSERT INTO cnatsp VALUES ('GLAIS', 'Glaisière');
INSERT INTO cnatsp VALUES ('GRAVE', 'Gravière');
INSERT INTO cnatsp VALUES ('HAIES', 'Haies fruitières');
INSERT INTO cnatsp VALUES ('HERB', 'Herbage');
INSERT INTO cnatsp VALUES ('HETRE', 'Hêtres');
INSERT INTO cnatsp VALUES ('HIST', 'Dépendances de monuments historiques');
INSERT INTO cnatsp VALUES ('HORT', 'Jardins horticoles');
INSERT INTO cnatsp VALUES ('HOUBL', 'Houblon');
INSERT INTO cnatsp VALUES ('HTIGE', 'Vergers exploités en hautes tiges');
INSERT INTO cnatsp VALUES ('HUITR', 'Parc à huîtres');
INSERT INTO cnatsp VALUES ('IMM', 'Dépendances d''ensemble immobilier');
INSERT INTO cnatsp VALUES ('IMPRO', 'Lande improductive');
INSERT INTO cnatsp VALUES ('INTEN', 'Verger industriel');
INSERT INTO cnatsp VALUES ('JARD', 'Jardin d’agrément');
INSERT INTO cnatsp VALUES ('JETT', 'Jettins');
INSERT INTO cnatsp VALUES ('JOUAL', 'Joualle');
INSERT INTO cnatsp VALUES ('KIWIS', 'Kiwis');
INSERT INTO cnatsp VALUES ('LAC', 'Lac');
INSERT INTO cnatsp VALUES ('LAGUN', 'Lagune');
INSERT INTO cnatsp VALUES ('LAVOI', 'Lavoir');
INSERT INTO cnatsp VALUES ('LEGUM', 'Légumière de plein champ');
INSERT INTO cnatsp VALUES ('MAQUI', 'Maquis');
INSERT INTO cnatsp VALUES ('MARAI', 'Pré marais');
INSERT INTO cnatsp VALUES ('MARAM', 'Jardin maraîcher aménagé');
INSERT INTO cnatsp VALUES ('MARE', 'Mare');
INSERT INTO cnatsp VALUES ('MAREC', 'Marécage');
INSERT INTO cnatsp VALUES ('MARN', 'Marnière');
INSERT INTO cnatsp VALUES ('MARNA', 'Jardin maraîcher non aménagé');
INSERT INTO cnatsp VALUES ('MELEZ', 'Mélèzes');
INSERT INTO cnatsp VALUES ('MOTTE', 'Mottes');
INSERT INTO cnatsp VALUES ('MUR', 'Mûraies ou mûriers (vergers)');
INSERT INTO cnatsp VALUES ('NATUR', 'Bois naturel');
INSERT INTO cnatsp VALUES ('NOISE', 'Noiseraie ou noisetiers');
INSERT INTO cnatsp VALUES ('NOYER', 'Noyeraie ou noyers');
INSERT INTO cnatsp VALUES ('NPECH', 'Etang non potable');
INSERT INTO cnatsp VALUES ('OLIVE', 'Olivaies ou oliviers');
INSERT INTO cnatsp VALUES ('ORANG', 'Orangers (vergers)');
INSERT INTO cnatsp VALUES ('ORME', 'Ormaie ou ormes');
INSERT INTO cnatsp VALUES ('PACAG', 'Pacage');
INSERT INTO cnatsp VALUES ('PAFEU', 'Pare-feux');
INSERT INTO cnatsp VALUES ('PALMI', 'Bois palmiste');
INSERT INTO cnatsp VALUES ('PARC', 'Parc');
INSERT INTO cnatsp VALUES ('PASS', 'Passage (non groupe)');
INSERT INTO cnatsp VALUES ('PATIS', 'Pâtis');
INSERT INTO cnatsp VALUES ('PATUR', 'Pâture plantée');
INSERT INTO cnatsp VALUES ('PECH', 'Etangs pêchables');
INSERT INTO cnatsp VALUES ('PECHE', 'Pêchers');
INSERT INTO cnatsp VALUES ('PEPIN', 'Pépinières');
INSERT INTO cnatsp VALUES ('PIEDS', 'Pieds-mères (vignes)');
INSERT INTO cnatsp VALUES ('PIERR', 'Pierraille, pierrier');
INSERT INTO cnatsp VALUES ('PIN', 'Pins');
INSERT INTO cnatsp VALUES ('PLAGE', 'Plage');
INSERT INTO cnatsp VALUES ('PLATR', 'Plâtrière');
INSERT INTO cnatsp VALUES ('PLVEN', 'Vergers de plein vent');
INSERT INTO cnatsp VALUES ('POIRE', 'Poiriers');
INSERT INTO cnatsp VALUES ('POMME', 'Pommiers');
INSERT INTO cnatsp VALUES ('POTAG', 'Potagers');
INSERT INTO cnatsp VALUES ('PROTE', 'Bois de protection');
INSERT INTO cnatsp VALUES ('PRUNE', 'Pruniers');
INSERT INTO cnatsp VALUES ('RAIS', 'Raisins de table');
INSERT INTO cnatsp VALUES ('RESER', 'Réservoir');
INSERT INTO cnatsp VALUES ('RESIN', 'Résineux');
INSERT INTO cnatsp VALUES ('RIVAG', 'Rivage (bois de)');
INSERT INTO cnatsp VALUES ('RIZ', 'Rizière');
INSERT INTO cnatsp VALUES ('ROC', 'Rocs ou rochers');
INSERT INTO cnatsp VALUES ('ROUI', 'Routoir ou roussoir');
INSERT INTO cnatsp VALUES ('RUE', 'Rue');
INSERT INTO cnatsp VALUES ('RUINE', 'Ruines');
INSERT INTO cnatsp VALUES ('SABLE', 'Sablière');
INSERT INTO cnatsp VALUES ('SALIN', 'Marais salant');
INSERT INTO cnatsp VALUES ('SAPIN', 'Sapins ou sapinière');
INSERT INTO cnatsp VALUES ('SART', 'Sartières');
INSERT INTO cnatsp VALUES ('SAULE', 'Saulaie ou saussaie');
INSERT INTO cnatsp VALUES ('SERRE', 'Serre');
INSERT INTO cnatsp VALUES ('SOL', 'Sols');
INSERT INTO cnatsp VALUES ('SOURC', 'Source');
INSERT INTO cnatsp VALUES ('SPORT', 'Terrain de sport');
INSERT INTO cnatsp VALUES ('TAMAR', 'Tamarin');
INSERT INTO cnatsp VALUES ('TAUZ', 'Taillis tauzin');
INSERT INTO cnatsp VALUES ('TERRI', 'Terrils');
INSERT INTO cnatsp VALUES ('TOURB', 'Tourbière');
INSERT INTO cnatsp VALUES ('TOUYA', 'Touyas');
INSERT INTO cnatsp VALUES ('VADC', 'Vins d''appellation d''origine contrôlée');
INSERT INTO cnatsp VALUES ('VAGUE', 'Terrain vague');
INSERT INTO cnatsp VALUES ('VANIL', 'Vanille');
INSERT INTO cnatsp VALUES ('VAOC', 'Vins d''appellation d''origine contrôlée');
INSERT INTO cnatsp VALUES ('VCHAS', 'Chasselas');
INSERT INTO cnatsp VALUES ('VDQS', 'Vins délimités de qualité supérieure');
INSERT INTO cnatsp VALUES ('VIGNE', 'Vigne');
INSERT INTO cnatsp VALUES ('VIVIE', 'Vivier');

-- nomenclature ccolloc (sufexoneration, pevexoneration)
INSERT INTO ccolloc VALUES ('TC', 'Toutes collectivités');
INSERT INTO ccolloc VALUES ('C', 'Commune => l''exonération porte sur la seule part communale');
INSERT INTO ccolloc VALUES ('D', 'Département => l''exonération porte sur la seule part départementale');
INSERT INTO ccolloc VALUES ('R', 'Région => l''exonération porte sur la seule part régionale');
INSERT INTO ccolloc VALUES ('GC', 'Groupement de communes');
INSERT INTO ccolloc VALUES ('A', 'l''exonération porte sur la taxe additionnelle');
-- 2018
INSERT INTO ccolloc VALUES ('TS', 'Taxe spéciale d’équipement (TSE)');
INSERT INTO ccolloc VALUES ('OM', 'Taxe sur l’enlèvement des ordures ménagères (TEOM)');

-- nomenclature gnexts (sufexoneration)
INSERT INTO gnexts VALUES ('TU ', 'Exo pour terrains nouvellement plantés en arbres truffiers – art. 1395 B-II du CGI');
INSERT INTO gnexts VALUES ('OL ', 'Exonération pour terrains plantés en oliviers (sur délibération)');
INSERT INTO gnexts VALUES ('TR ', 'Exonération pour plantation de truffiers (sur délibération)');
INSERT INTO gnexts VALUES ('NO ', 'Exonération pour plantation de noyers (sur délibération)');
INSERT INTO gnexts VALUES ('PB ', 'Exonération pour plantation de bois (groupe 5),');
INSERT INTO gnexts VALUES ('TA ', 'Exonération des terres agricoles (groupes de culture 1 à 6, 8 et 9)');
INSERT INTO gnexts VALUES ('HP ', 'Exonération temporaire (exonération totale en zone naturelle)');
INSERT INTO gnexts VALUES ('HR ', 'Exonération temporaire (exonération de 50% sur proposition de la CCID)');
INSERT INTO gnexts VALUES ('NA ', 'Exonération Natura 2000');
INSERT INTO gnexts VALUES ('PP', 'Peupliers - plantations et semis Exonération temporaire de 10 ans');
INSERT INTO gnexts VALUES ('PR', 'Résineux - plantations et semis - futaies, taillis sous futaie en régénération naturelle Exonération temporaire de 30 ans');
INSERT INTO gnexts VALUES ('PF', 'Feuillus - plantations et semis - futaies, taillis sous futaie en régénération naturelle Exonération temporaire de 50 ans');
INSERT INTO gnexts VALUES ('ER', 'Terrains boisés présentant un état de futaie irrégulière en équilibre de régénération Exonération partielle 25% de 15 ans, Renouvelable (% dans PEXN)');
INSERT INTO gnexts VALUES ('VG', 'Vergers, cultures fruitières d’arbres et d’arbustes, vignes.');
INSERT INTO gnexts VALUES ('HQ', 'Exonération de 50 % pendant 5 ans pour les subdivisions fiscales dont la nature de culture est soit pré, soit landes');
INSERT INTO gnexts VALUES ('HS', 'Exonération de 100 % pendant 5 ans pour les subdivisions fiscales dont la nature de culture est soit pré, soit landes');

-- nomenclature ccoeva (local10)
INSERT INTO ccoeva VALUES ('A', 'Méthode comptable');
INSERT INTO ccoeva VALUES ('B', 'Evaluation d’après le bail');
INSERT INTO ccoeva VALUES ('C', 'Evaluation par comparaison');
INSERT INTO ccoeva VALUES ('D', 'Evaluation par voie d’appréciation directe');
INSERT INTO ccoeva VALUES ('E', 'Evaluation spécifique aux transformateurs électriques et appareils à gaz');
INSERT INTO ccoeva VALUES ('T', 'Evaluation par barème (locaux commerciaux et assimilés)');


-- nomenclature dteloc (local10)
INSERT INTO dteloc VALUES ('1', 'Maison');
INSERT INTO dteloc VALUES ('2', 'Appartement');
INSERT INTO dteloc VALUES ('3', 'Dépendances');
INSERT INTO dteloc VALUES ('4', 'Local commercial ou industriel');
INSERT INTO dteloc VALUES ('5', 'DOM = maison dans descriptif');
INSERT INTO dteloc VALUES ('6', 'DOM = appartement sans descriptif');
INSERT INTO dteloc VALUES ('7', 'DOM = dépendance sans descriptif');
INSERT INTO dteloc VALUES ('8', 'Locaux de groupe 4 : évaluation tarifaire (non présente depuis 94)');
-- nomenclature ccoplc (local10)
INSERT INTO ccoplc VALUES (' ', 'Construction particulière');
INSERT INTO ccoplc VALUES ('R', 'Construction classée sur sol d''autrui lors de l''initialisation Majic2 (local, hors pdl, avec attribution différente de la parcelle d''assise)');
INSERT INTO ccoplc VALUES ('U', 'Chute d''eau, barrage');
INSERT INTO ccoplc VALUES ('V', 'Construction édifiée sur le domaine public');
INSERT INTO ccoplc VALUES ('W', 'Construction édifiée sous le domaine public');
INSERT INTO ccoplc VALUES ('X', 'Voies ferrées établies sur le terrain d''autrui ou sur le domaine public et dont l''assise ne forme pas parcelle');
INSERT INTO ccoplc VALUES ('Y', 'Construction édifiée sous le domaine cadastre');
INSERT INTO ccoplc VALUES ('Z', 'Construction édifiée sur sol d''autrui');
-- nomenclature cconlc (local10)
INSERT INTO cconlc VALUES ('AP', 'Appartement');
INSERT INTO cconlc VALUES ('AT', 'Antenne téléphone');
INSERT INTO cconlc VALUES ('AU', 'Autoroute');
INSERT INTO cconlc VALUES ('CA', 'Commerce sans boutique');
INSERT INTO cconlc VALUES ('CB', 'Local divers');
INSERT INTO cconlc VALUES ('CD', 'Dépendance commerciale');
INSERT INTO cconlc VALUES ('CH', 'Chantier');
INSERT INTO cconlc VALUES ('CM', 'Commerce avec boutique');
INSERT INTO cconlc VALUES ('DC', 'Dépendance lieux communs');
INSERT INTO cconlc VALUES ('DE', 'Dépendance bâtie isolée');
INSERT INTO cconlc VALUES ('LC', 'Local commun');
INSERT INTO cconlc VALUES ('MA', 'Maison');
INSERT INTO cconlc VALUES ('ME', 'Maison exceptionnelle');
INSERT INTO cconlc VALUES ('MP', 'Maison partagée par une limite territoriale');
INSERT INTO cconlc VALUES ('SM', 'Sol de maison');
INSERT INTO cconlc VALUES ('U', 'Etablissement industriel');
INSERT INTO cconlc VALUES ('U1', 'Gare');
INSERT INTO cconlc VALUES ('U2', 'Gare : Triage');
INSERT INTO cconlc VALUES ('U3', 'Gare : Atelier matériel');
INSERT INTO cconlc VALUES ('U4', 'Gare : Atelier magasin');
INSERT INTO cconlc VALUES ('U5', 'Gare : Dépôt - Titulaire');
INSERT INTO cconlc VALUES ('U6', 'Gare : Dépôt - Réel');
INSERT INTO cconlc VALUES ('U7', 'Gare : Matériel transport');
INSERT INTO cconlc VALUES ('U8', 'Gare : Entretien matériel roulant');
INSERT INTO cconlc VALUES ('U9', 'Gare : Station usine');
INSERT INTO cconlc VALUES ('UE', 'Transformateur électrique');
INSERT INTO cconlc VALUES ('UG', 'Appareil à gaz');
INSERT INTO cconlc VALUES ('US', 'Etablissement industriel');
-- nomenclature top48a (local10)
INSERT INTO top48a VALUES ('1', 'pev imposé au loyer');
INSERT INTO top48a VALUES ('0', 'pev imposé à la vl');
-- nomenclature dnatlc (local10)
INSERT INTO dnatlc VALUES ('A', 'Local occupé par un apprenti ou un salarié agricole');
INSERT INTO dnatlc VALUES ('D', 'DOM = habitation principale occupée par le propriétaire');
INSERT INTO dnatlc VALUES ('L', 'Location autre que propriétaire ou usufruitier');
INSERT INTO dnatlc VALUES ('P', 'Occupé par le propriétaire ou l’usufruitier');
INSERT INTO dnatlc VALUES ('T', 'Location, non affectée à l''habitation, soumise à TVA');
INSERT INTO dnatlc VALUES ('V', 'Vacant');
-- nomenclature dnatcg
INSERT INTO dnatcg VALUES ('AC', 'Addition de construction');
INSERT INTO dnatcg VALUES ('CA', 'Changement d’affectation');
INSERT INTO dnatcg VALUES ('CC', 'Changement de consistance');
INSERT INTO dnatcg VALUES ('CI', 'Changement de l''identification du local');
INSERT INTO dnatcg VALUES ('CN', 'Construction nouvelle');
INSERT INTO dnatcg VALUES ('CU', 'Changement d’utilisation');
INSERT INTO dnatcg VALUES ('CX', 'Modification suite à contentieux');
INSERT INTO dnatcg VALUES ('DL', 'Division de locaux');
INSERT INTO dnatcg VALUES ('DP', 'Démolition partielle');
INSERT INTO dnatcg VALUES ('DT', 'Démolition totale');
INSERT INTO dnatcg VALUES ('ME', 'Modification des critères d’évaluation');
INSERT INTO dnatcg VALUES ('RL', 'Réunion de locaux');
-- nomenclature gimtom
INSERT INTO gimtom VALUES ('', 'Imposable TEOM');
INSERT INTO gimtom VALUES ('E', 'Exonération de TEOM de droit pour les locaux: en exonération NI, EP, CR, DR autre que les locaux d’habitation; de code nature U, US, UE, UG, U1 à U9, AU ; loués par des personnes publiques et affectées à un service public');
INSERT INTO gimtom VALUES ('D', 'Exonération TEOM sur délibération de la collectivité gestionnaire de TEOM (locaux à usage industriel ou commercial, locaux dotés d’un incinérateur)');
INSERT INTO gimtom VALUES ('V', 'Local d’habitation en exonération permanente EP/CR/DR sans fonctionnaire logé (vacants)');
-- nomenclature hlmsem (local10)
INSERT INTO hlmsem VALUES ('5', 'hlm');
INSERT INTO hlmsem VALUES ('6', 'sem');
-- nomenclature ccoaff (pev)
INSERT INTO ccoaff VALUES ('B', 'Bâtiment industriel (lie a ccoeva = A ou E)');
INSERT INTO ccoaff VALUES ('C', 'Commerce');
INSERT INTO ccoaff VALUES ('H', 'Habitation');
INSERT INTO ccoaff VALUES ('K', 'Locaux administratifs non passibles de la TH');
INSERT INTO ccoaff VALUES ('L', 'Hôtel');
INSERT INTO ccoaff VALUES ('P', 'Professionnel');
INSERT INTO ccoaff VALUES ('S', 'Biens divers passibles de la TH');
INSERT INTO ccoaff VALUES ('T', 'Terrain industriel (lie à ccoeva = A ou E)');
-- nomenclature gnexpl (pev)
INSERT INTO gnexpl VALUES ('CD', 'Exonération permanente des parts communale et départementale (biens d''une région situés dans une autre région)');
INSERT INTO gnexpl VALUES ('CR', 'Exonération permanente des parts communale et régionale (biens d''un département situés dans un autre département)');
INSERT INTO gnexpl VALUES ('DR', 'Exonération permanente des parts départementale et régionale (biens d''une commune situés dans une autre commune)');
INSERT INTO gnexpl VALUES ('EP', 'Exonération permanente');
INSERT INTO gnexpl VALUES ('NI', 'Non imposable');
INSERT INTO gnexpl VALUES ('PP', 'Exonération de pev secondaire de bien indivis');
INSERT INTO gnexpl VALUES ('DM', 'exonération des parts intercommunale, départementale, TSE et TEOM pour un immeuble appartenant à une commune et situé sur le territoire d’une autre commune appartenant à la métropole de Lyon');
INSERT INTO gnexpl VALUES ('CM', 'exonération des parts communale, TSE et TEOM pour un immeuble appartenant à une commune et situé sur le territoire d’une autre commune appartenant à la métropole de Lyon');
INSERT INTO gnexpl VALUES ('GM', 'transfert de propriétés bâties par l’État aux grands ports maritimes affectés à un service public ou d’utilité générale et non productifs de revenus');

-- nomenclature pour ccthp (Occupation du local)
INSERT INTO ccthp VALUES ('B', 'Locaux meublés à usage d’habitation faisant l’objet de locations occasionnelles permanentes ou saisonnières (TH)');
INSERT INTO ccthp VALUES ('D', 'Division fiscale (CFE) ou local démoli (TH)');
INSERT INTO ccthp VALUES ('F', 'Fonctionnaire logé (TH)');
INSERT INTO ccthp VALUES ('G', 'Occupation à titre gratuit (TH)');
INSERT INTO ccthp VALUES ('L', 'Occupation par un locataire (TH)');
INSERT INTO ccthp VALUES ('N', 'Local dépendance non imposable (TH)');
INSERT INTO ccthp VALUES ('P', 'Occupation par le propriétaire (TH)');
INSERT INTO ccthp VALUES ('R', 'Occupation par un artisan exonéré (CFE)');
INSERT INTO ccthp VALUES ('T', 'Local imposé à la taxe professionnelle (TH)');
INSERT INTO ccthp VALUES ('U', 'Utilisation commune (CFE)');
INSERT INTO ccthp VALUES ('V', 'Local vacant');
INSERT INTO ccthp VALUES ('X', 'Occupation par bail rural (TH)');
INSERT INTO ccthp VALUES ('', 'Non défini');

-- nomenclature pour cbtabt (Code exonération HLM Zone sensible)
INSERT INTO cbtabt VALUES ('AS', 'Antisismique dans les DOM');
INSERT INTO cbtabt VALUES ('CV', 'Logements sociaux situés dans un quartier prioritaire – Contrat de ville');

-- nomenclature gnextl (pevexoneration)
INSERT INTO gnextl VALUES ('CD', 'Exonération permanente des parts communale et départementale (biens d''une région situés dans une autre région)');
INSERT INTO gnextl VALUES ('CR', 'Exonération permanente des parts communale et régionale (biens d''un département situés dans un autre département)');
INSERT INTO gnextl VALUES ('DR', 'Exonération permanente des parts départementale et régionale (biens d''une commune situés dans une autre commune)');
INSERT INTO gnextl VALUES ('EP', 'Exonération permanente');
INSERT INTO gnextl VALUES ('NI', 'Non imposable');
INSERT INTO gnextl VALUES ('PP', 'Exonération de pev secondaire de bien indivis');
INSERT INTO gnextl VALUES ('AD', 'Droit commun (2 ans) - addition de construction');
INSERT INTO gnextl VALUES ('AE', 'Exonération de 20 ans en faveur des logements sociaux qui respectent un certain nombre de normes environnementales pour additions de constructions');
INSERT INTO gnextl VALUES ('AF', '2 ans pour addition de construction avec prêtconventionne, PAP ou PLA');
INSERT INTO gnextl VALUES ('AL', 'Exo de 15 ans pour logements sociaux (AC)');
INSERT INTO gnextl VALUES ('AP', 'Exonération annuelle pour installation antipollution');
INSERT INTO gnextl VALUES ('AQ', 'Exonération de 15 ans pour addition de construction antérieure au 01/01/1973');
INSERT INTO gnextl VALUES ('AS', 'Abattement de 30% pour les locaux sociaux situés dans les DOM et équipés contre les risques naturels');
INSERT INTO gnextl VALUES ('AT', 'Exonération de 30 ans pour les logements sociaux respectant certains critères de qualité environnementale (addition de construction).');
INSERT INTO gnextl VALUES ('AU', 'Exonération de 25 ans pour les logements financés au moyen de prêts aidés par l''Etat (addition de construction)');
INSERT INTO gnextl VALUES ('AV', 'Exonération de 25 ans pour les logements financés au moyen de prêts aidés par l''Etat (addition de construction)');
INSERT INTO gnextl VALUES ('AW', 'Exonération de 25 ans pour les logements financés au moyen de prêts aidés par l''Etat (addition de construction)');
INSERT INTO gnextl VALUES ('AX', 'Longue durée (10 ans) - addition de construction');
INSERT INTO gnextl VALUES ('AY', 'Exo de 15 ans pour logements sociaux (AC)');
INSERT INTO gnextl VALUES ('AZ', 'Exonération de 30 ans pour les logements sociaux respectant certains critères de qualité environnementale (addition de construction).');
INSERT INTO gnextl VALUES ('BE', 'Local situé dans un bassin d''emploi à redynamiser. Article 1383 H du CGI.');
INSERT INTO gnextl VALUES ('CE', 'Abattement de 5 ans pour cession relevant de l’article 1388 sexies du CGI (Mayotte)');
INSERT INTO gnextl VALUES ('DF', 'Exonération pour bâtiment déshydratation des fourrages.');
INSERT INTO gnextl VALUES ('EA', 'Economiquement faible - type A');
INSERT INTO gnextl VALUES ('EB', 'Economiquement faible - type B');
INSERT INTO gnextl VALUES ('EC', 'Economiquement faible - type C');
INSERT INTO gnextl VALUES ('EE', 'Exonération économiquement faible (ECF) de type E.');
INSERT INTO gnextl VALUES ('EF', 'Exonération économiquement faible (ECF) de type F.');
INSERT INTO gnextl VALUES ('EI', 'Exonération pour les jeunes entreprises innovantes');
INSERT INTO gnextl VALUES ('EN', 'Exonération entreprise nouvelle.');
INSERT INTO gnextl VALUES ('GS', 'Exo pour groupement de coopération sanitaire');
INSERT INTO gnextl VALUES ('HU', 'Exo de 15 ans pour logements sociaux acquis ou aménagés');
INSERT INTO gnextl VALUES ('HY', 'Exo de 25 ans pour logements sociaux acquis ou aménagés');
INSERT INTO gnextl VALUES ('LA', 'Durée variable - totale ou partielle - PLA');
INSERT INTO gnextl VALUES ('LM', 'Local situé dans une zone de revitalisation rurale. Article 1383 E bis du CGI.');
INSERT INTO gnextl VALUES ('LR', 'Durée variable - totale ou partielle habilitation');
INSERT INTO gnextl VALUES ('LW', 'Exonération de 25 ans pour les logements acquis avec l''aide de l''Etat en vue de leur location.');
INSERT INTO gnextl VALUES ('LY', 'Prorogation de 10 ans de l’exonération « LE » prévue à l’art. 1384 C du CGI');
INSERT INTO gnextl VALUES ('ND', 'Droit commun (2 ans) - construction nouvelle');
INSERT INTO gnextl VALUES ('NE', 'Exonération de 20 ans en faveur des logements sociaux qui respectent un certain nombre de normes environnementales pour constructions nouvelles');
INSERT INTO gnextl VALUES ('NF', '2 ans pour construction nouvelle avec prêt conventionne, PAP ou PLA');
INSERT INTO gnextl VALUES ('NL', 'Exo de 15 ans pour logements sociaux (CN)');
INSERT INTO gnextl VALUES ('NQ', 'Exonération de 15 ans pour construction nouvelle antérieure au 01/01/1973');
INSERT INTO gnextl VALUES ('NT', 'Exonération de 30 ans pour les logements sociaux respectant certains critères de qualité environnementale (construction nouvelle).');
INSERT INTO gnextl VALUES ('NU', 'Exonération de 25 ans pour les logements financés au moyen de prêts aidés par l''Etat (construction nouvelle)');
INSERT INTO gnextl VALUES ('NV', 'Exonération de 25 ans pour les logements financés au moyen de prêts aidés par l''Etat (construction nouvelle)');
INSERT INTO gnextl VALUES ('NW', 'Exonération de 25 ans pour les logements financés au moyen de prêts aidés par l''Etat (construction nouvelle)');
INSERT INTO gnextl VALUES ('NX', 'Longue durée (10 ans) - construction nouvelle');
INSERT INTO gnextl VALUES ('NY', 'Exo de 25 ans pour logements sociaux (CN)');
INSERT INTO gnextl VALUES ('NZ', 'Exonération de 30 ans pour les logements sociaux respectant certains critères de qualité environnementale (construction nouvelle).');
INSERT INTO gnextl VALUES ('PC', 'Exo de 5 ans pour locaux situés dans un pôle de compétitivité art. 1383 F du CGI');
INSERT INTO gnextl VALUES ('PE', 'Prolongation a durée variable d’exonération de droit commun');
INSERT INTO gnextl VALUES ('PX', 'Prolongation exonérations NX et AX (5 ans maxi)');
INSERT INTO gnextl VALUES ('RA', 'Exonération de certains établissements industriels durée indéterminée.');
INSERT INTO gnextl VALUES ('RC', 'Exo pour bail à réhabilitation pris à compter du 01/01/2005 art. 1384 B, 1586 B et 1599 ter E du CGI');
INSERT INTO gnextl VALUES ('RQ', 'Local achevé avant la mise en place d''un plan de prévention des risques technologiques. Article 1383 G du CGI.');
INSERT INTO gnextl VALUES ('RW', 'Local achevé avant le 01/01/1989 ayant fait l''objet de dépenses destinées à économiser l''énergie. Article 1383-O B du CGI.');
INSERT INTO gnextl VALUES ('ZF', 'Exonération zone franche.');
INSERT INTO gnextl VALUES ('ZR', 'Exo de 15 ans pour locaux situés dans une zone de revitalisation rurale art. 1383 E du CGI');
INSERT INTO gnextl VALUES ('ZS', 'Abattement ZUS 30 % HLM SEM (obsolète à partir du format 2012)');
INSERT INTO gnextl VALUES ('ZT', 'Logement topé ZUS');
INSERT INTO gnextl VALUES ('ZU', 'Exonération pour nouvelles zones franches');
INSERT INTO gnextl VALUES ('ZV', 'Exo de 5 ans pour zone franche urbaine de 3éme génération art. 1384 C bis du CGI');
INSERT INTO gnextl VALUES ('LG', 'Exonération établissements publics supérieurs sous contrat avec des sociétés dont le capital est entièrement public.');
INSERT INTO gnextl VALUES ('P1', 'Abattement 1ère année sur outillages, équipements et installations spécifiques de manutention portuaires (100 %).');
INSERT INTO gnextl VALUES ('P2', 'Abattement 2ème année sur outillages, équipements et installations spécifiques de manutention portuaires (100 %)');
INSERT INTO gnextl VALUES ('P3', 'Abattement 3ème, 4ème et 5ème années sur outillages, équipements et installations spécifiques de manutention');
INSERT INTO gnextl VALUES ('LE', 'Exonération de 15 ans pour les logements acquis avec l’aide de l’aide de l’Etat en vue de leur location');
INSERT INTO gnextl VALUES ('LI', 'Exonération de 15 ans pour les logements sociaux acquis d’un organisme mentionné à l’article L 411.5 du Code de la construction et de l’habitation.');
INSERT INTO gnextl VALUES ('AK', 'Exonération de 20 ans pour les logements intermédiaires loués dans les conditions de l’article 279-0 bis A (addition de construction) – art. 1384-0 A du CGI');
INSERT INTO gnextl VALUES ('NK', 'Exonération de 20 ans pour les logements intermédiaires loués dans les conditions de l’article 279-0 bis A (construction nouvelle) – art. 1384-0 A du CGI');
INSERT INTO gnextl VALUES ('RT', 'Abattement de 25 % pour les locaux faisant l’objet d’une convention ou d''un contrat de résidence temporaire – art. 1388 quinquies A du CGI');
INSERT INTO gnextl VALUES ('UM', 'Exonération de 5 ans pour les usines de méthanisation - art. 1387 A du CGI');

INSERT INTO gnextl VALUES ('GP', 'grand port maritime');
INSERT INTO gnextl VALUES ('RF', 'requalification de copropriétés dégradées d’intérêt
national acquises par un établissement public foncier');
INSERT INTO gnextl VALUES ('QP', 'quartier prioritaire');
INSERT INTO gnextl VALUES ('CV', 'contrat de ville');
INSERT INTO gnextl VALUES ('RI', 'recherche industrielle');
INSERT INTO gnextl VALUES ('G1', 'transfert de propriétés bâties par l’État aux grands ports maritimes non affectés à un service public ou d’utilité générale ou productifs de revenus – 1ère année - 100 %');
INSERT INTO gnextl VALUES ('G2', 'transfert de propriétés bâties par l’État aux grands ports maritimes non affectés à un service public ou d’utilité générale ou productifs de revenus - 2ème année - 100 %');
INSERT INTO gnextl VALUES ('G3', 'transfert de propriétés bâties par l’État aux grands ports maritimes non affectés à un service public ou d’utilité générale ou productifs de revenus - 3ème année - 75 %');
INSERT INTO gnextl VALUES ('G4', 'transfert de propriétés bâties par l’État aux grands ports maritimes non affectés à un service public ou d’utilité générale ou productifs de revenus - 4ème année - 50 %');
INSERT INTO gnextl VALUES ('G5', 'transfert de propriétés bâties par l’État aux grands ports maritimes non affectés à un service public ou d’utilité générale ou productifs de revenus - 5ème année - 25 %');

INSERT INTO gnextl VALUES ('BH', 'Locaux à usage de bureau transformés en habitation principale');
INSERT INTO gnextl VALUES ('EW', 'Exonération ECF de droits acquis');
INSERT INTO gnextl VALUES ('E1', 'Exonération ECF de droit commun – 100 % – 1ère année');
INSERT INTO gnextl VALUES ('E2', 'Exonération ECF de droit commun – 100 % – 2 e année');
INSERT INTO gnextl VALUES ('E3', 'Exonération ECF de droit commun – 67 % – 3 e année');
INSERT INTO gnextl VALUES ('E4', 'Exonération ECF de droit commun – 33 % – 4 e année');
INSERT INTO gnextl VALUES ('MS', 'Maison de santé');
INSERT INTO gnextl VALUES ('PI', 'Locaux situés sur des terrains pollués dans le périmètre d’un projet d’intérêt général');
INSERT INTO gnextl VALUES ('QV', 'Locaux HLM se situant dans un quartier prioritaire');
INSERT INTO gnextl VALUES ('ZQ', 'Abattement de 30 % pour les locaux d’habitation situés dans les immeubles collectifs issus de la transformation de locaux industriels ou commerciaux dans le périmètre des quartiers prioritaires de la politique de la ville');
-- 2018
INSERT INTO gnextl VALUES ('BS', 'Abattement de 30 % pour les logements faisant l’objet d’un bail réel solidaire');
INSERT INTO gnextl VALUES ('ES', 'Équipements souterrains indissociables des casiers des installations de stockage de déchets non dangereux');
INSERT INTO gnextl VALUES ('MA', 'Minoration de 60 % de la valeur locative des locaux d’habitation situés à Mayotte');

-- nomenclature cconad (pevprincipale, pevdependances)
INSERT INTO cconad VALUES ('CV', 'Cave');
INSERT INTO cconad VALUES ('GA', 'Garage');
INSERT INTO cconad VALUES ('GR', 'Grenier');
INSERT INTO cconad VALUES ('TR', 'Terrasse');
INSERT INTO cconad VALUES ('BC', 'Bûcher');
INSERT INTO cconad VALUES ('BD', 'Buanderie');
INSERT INTO cconad VALUES ('BX', 'Box');
INSERT INTO cconad VALUES ('CD', 'Chambre de domestique');
INSERT INTO cconad VALUES ('CL', 'Cellier');
INSERT INTO cconad VALUES ('DC', 'Dépendance de local commun');
INSERT INTO cconad VALUES ('GC', 'Grenier/cave');
INSERT INTO cconad VALUES ('GP', 'Garage/parking');
INSERT INTO cconad VALUES ('JH', 'Jardin d''hiver');
INSERT INTO cconad VALUES ('PA', 'Elément de pur agrément');
INSERT INTO cconad VALUES ('PI', 'Pièce indépendante');
INSERT INTO cconad VALUES ('PK', 'Parking');
INSERT INTO cconad VALUES ('PS', 'Piscine');
INSERT INTO cconad VALUES ('RS', 'Remise');
INSERT INTO cconad VALUES ('SR', 'Serre');
INSERT INTO cconad VALUES ('TT', 'Toiture-terrasse');
-- nomenclature ctpdl (pdl)
INSERT INTO ctpdl VALUES ('BND', 'Libellé BND');
INSERT INTO ctpdl VALUES ('CL', 'Libellé CL');
INSERT INTO ctpdl VALUES ('CV', 'Libellé CV');
INSERT INTO ctpdl VALUES ('TF', 'Libellé TF');
INSERT INTO ctpdl VALUES ('CLV', 'Libellé CLV');
INSERT INTO ctpdl VALUES ('MP', 'Libellé MP');
-- nomenclature cconlo (lots)
INSERT INTO cconlo VALUES ('1', 'lot non bâti');
INSERT INTO cconlo VALUES ('2', 'lot bâti');
INSERT INTO cconlo VALUES ('3', 'lot mixte');
INSERT INTO cconlo VALUES ('4', 'assise de pdl');
INSERT INTO cconlo VALUES ('5', 'lot particulier');
INSERT INTO cconlo VALUES ('6', 'lot multi-communes');
-- nomenclature ccodro (proprietaire)
INSERT INTO ccodro VALUES ('P', 'PROPRIETAIRE');
INSERT INTO ccodro VALUES ('U', 'USUFRUITIER (ASSOCIE AVEC N)');
INSERT INTO ccodro VALUES ('N', 'NU-PROPRIETAIRE (ASSOCIE AVEC U)');
INSERT INTO ccodro VALUES ('B', 'BAILLEUR A CONSTRUCTION (ASSOCIE AVEC R)');
INSERT INTO ccodro VALUES ('R', 'PRENEUR A CONSTRUCTION (ASSOCIE AVEC B)');
INSERT INTO ccodro VALUES ('F', 'FONCIER (ASSOCIE AVEC D OU T)');
INSERT INTO ccodro VALUES ('T', 'TENUYER (ASSOCIE AVEC F)');
INSERT INTO ccodro VALUES ('D', 'DOMANIER (ASSOCIE AVEC F)');
INSERT INTO ccodro VALUES ('W', 'PRENEUR D''UN BAIL A REHABILITATION (ASSOCIE AVEC V)');
INSERT INTO ccodro VALUES ('A', 'LOCATAIRE-ATTRIBUTAIRE (ASSOCIE AVEC P)');
INSERT INTO ccodro VALUES ('E', 'EMPHYTEOTE (ASSOCIE AVEC P)');
INSERT INTO ccodro VALUES ('K', 'ANTICHRESISTE (ASSOCIE AVEC P)');
INSERT INTO ccodro VALUES ('L', 'FONCTIONNAIRE LOGE');
INSERT INTO ccodro VALUES ('G', 'GERANT,MANDATAIRE,GESTIONNAIRE');
INSERT INTO ccodro VALUES ('S', 'SYNDIC DE COPROPRIETE');
INSERT INTO ccodro VALUES ('H', 'ASSOCIE DANS UNE SOCIETE EN TRANSPARENCE FISCALE(ASSOCIE AVEC P)');
INSERT INTO ccodro VALUES ('O', 'AUTORISATION D’OCCUPATION TEMPORAIRE (70 ANS)');
INSERT INTO ccodro VALUES ('J', 'JEUNE AGRICULTEUR');
INSERT INTO ccodro VALUES ('Q', 'GESTIONNAIRE TAXE SUR LES BUREAUX (ILE DE FRANCE)');
INSERT INTO ccodro VALUES ('X', 'LA POSTE PROPRIETAIRE ET OCCUPANT');
INSERT INTO ccodro VALUES ('Y', 'LA POSTE OCCUPANT - NON PROPRIETAIRE');
INSERT INTO ccodro VALUES ('C', 'FIDUCIAIRE');
INSERT INTO ccodro VALUES ('M', 'OCCUPANT D’UNE PARCELLE APPARTENANT AU DEPARTEMENT DE MAYOTTE OU A L’ETAT (ASSOCIE A P).');

-- nomenclature ccodem (proprietaire)
INSERT INTO ccodem VALUES ('C', 'Un des copropriétaires');
INSERT INTO ccodem VALUES ('S', 'Succession de');
INSERT INTO ccodem VALUES ('L', 'Propriété en litige');
INSERT INTO ccodem VALUES ('I', 'Indivision simple');
INSERT INTO ccodem VALUES ('V', 'La veuve ou les héritiers de');
-- nomenclature gtoper (proprietaire)
INSERT INTO gtoper VALUES ('1', 'physique');
INSERT INTO gtoper VALUES ('2', 'morale');
-- nomenclature ccoqua (proprietaire)
INSERT INTO ccoqua VALUES ('1', 'M');
INSERT INTO ccoqua VALUES ('2', 'MME');
INSERT INTO ccoqua VALUES ('3', 'MLE');
-- nomenclature dnatpr (proprietaire)
INSERT INTO dnatpr VALUES ('ECF', 'Pers. physique : ECONOMIQUEMENT FAIBLE (NON SERVI)');
INSERT INTO dnatpr VALUES ('FNL', 'Pers. physique : FONCTIONNAIRE LOGE');
INSERT INTO dnatpr VALUES ('DOM', 'Pers. physique : PROPRIETAIRE OCCUPANT DOM');
INSERT INTO dnatpr VALUES ('HLM', 'Pers. Morale : OFFICE HLM');
INSERT INTO dnatpr VALUES ('SEM', 'Pers. Morale : SOCIETE D ECONOMIE MIXTE');
INSERT INTO dnatpr VALUES ('TGV', 'Pers. Morale : SNCF');
INSERT INTO dnatpr VALUES ('RFF', 'Pers. Morale : RESEAU FERRE DE FRANCE');
INSERT INTO dnatpr VALUES ('CLL', 'Pers. Morale : COLLECTIVITE LOCALE');
INSERT INTO dnatpr VALUES ('CAA', 'Pers. Morale : CAISSE ASSURANCE AGRICOLE');
-- nomenclature ccogrm (proprietaire)
INSERT INTO ccogrm VALUES ('0', 'PERSONNES MORALES NON REMARQUABLES');
INSERT INTO ccogrm VALUES ('1', 'ETAT');
INSERT INTO ccogrm VALUES ('2', 'REGION');
INSERT INTO ccogrm VALUES ('3', 'DEPARTEMENT');
INSERT INTO ccogrm VALUES ('4', 'COMMUNE');
INSERT INTO ccogrm VALUES ('5', 'OFFICE HLM');
INSERT INTO ccogrm VALUES ('6', 'PERSONNES MORALES REPRESENTANT DES SOCIETES');
INSERT INTO ccogrm VALUES ('7', 'COPROPRIETAIRE');
INSERT INTO ccogrm VALUES ('8', 'ASSOCIE');
INSERT INTO ccogrm VALUES ('9', 'ETABLISSEMENTS PUBLICS OU ARGANISMES ASSIMILES');
INSERT INTO ccogrm VALUES ('0A', 'CAAA en Alsace-Moselle - PERSONNES MORALES NON REMARQUABLES');
INSERT INTO ccogrm VALUES ('1A', 'CAAA en Alsace-Moselle - ETAT');
INSERT INTO ccogrm VALUES ('2A', 'CAAA en Alsace-Moselle - REGION');
INSERT INTO ccogrm VALUES ('3A', 'CAAA en Alsace-Moselle - DEPARTEMENT');
INSERT INTO ccogrm VALUES ('4A', 'CAAA en Alsace-Moselle - COMMUNE');
INSERT INTO ccogrm VALUES ('5A', 'CAAA en Alsace-Moselle - OFFICE HLM');
INSERT INTO ccogrm VALUES ('6A', 'CAAA en Alsace-Moselle - PERSONNES MORALES REPRESENTANT DES SOCIETES');
INSERT INTO ccogrm VALUES ('7A', 'CAAA en Alsace-Moselle - COPROPRIETAIRE');
INSERT INTO ccogrm VALUES ('8A', 'CAAA en Alsace-Moselle - ASSOCIE');
INSERT INTO ccogrm VALUES ('9A', 'CAAA en Alsace-Moselle - ETABLISSEMENTS PUBLICS OU ARGANISMES ASSIMILES');
-- nomenclature gtyp3 (proprietaire)
INSERT INTO gtyp3 VALUES ('2', '2 LIGNE SERVIE (FORMAT LIBRE)');
INSERT INTO gtyp3 VALUES ('9', 'LIGNE VIDE');
-- nomenclature gtyp4 (proprietaire)
INSERT INTO gtyp4 VALUES ('1', 'ADRESSE CODIFIEE 1');
INSERT INTO gtyp4 VALUES ('2', 'ADRESSE CODIFIEE 2');
INSERT INTO gtyp4 VALUES ('3', 'ADRESSE FORMATEE');
INSERT INTO gtyp4 VALUES ('4', 'ADRESSE BOITE POSTALE OU SERVICE');
INSERT INTO gtyp4 VALUES ('5', 'ADRESSE CEDEX');
INSERT INTO gtyp4 VALUES ('6', 'ADRESSE SECTEUR POSTAL');
INSERT INTO gtyp4 VALUES ('7', 'ADRESSE NON CODIFIEE, NON FORMATABLE');
INSERT INTO gtyp4 VALUES ('8', 'ADRESSE A L ETRANGER');
INSERT INTO gtyp4 VALUES ('9', 'LIGNE VIDE');
-- nomenclature gtyp5 (proprietaire)
INSERT INTO gtyp5 VALUES ('1', 'LIGNE SERVIE (COMMUNE OU LIEU-DIT) 1');
INSERT INTO gtyp5 VALUES ('2', 'LIGNE SERVIE (COMMUNE OU LIEU-DIT) 2');
INSERT INTO gtyp5 VALUES ('3', 'LIGNE SERVIE (COMMUNE OU LIEU-DIT) 3');
INSERT INTO gtyp5 VALUES ('4', 'LIGNE SERVIE FORMAT LIBRE');
INSERT INTO gtyp5 VALUES ('8', 'ADRESSE A L''ETRANGER (libellé de la ville)');
INSERT INTO gtyp5 VALUES ('9', 'LIGNE VIDE');
-- nomenclature gtyp6 (proprietaire)
INSERT INTO gtyp6 VALUES ('2', 'ADRESSE FORMATEE, sous la forme CODE POSTAL sur 5');
INSERT INTO gtyp6 VALUES ('3', 'ADRESSE A L''ETRANGER avec codification du pays en CCOPAY');
INSERT INTO gtyp6 VALUES ('4', 'ADRESSE A L''ETRANGER sans codification du pays.');
INSERT INTO gtyp6 VALUES ('5', 'ADRESSE INCODIFIABLE');
INSERT INTO gtyp6 VALUES ('6', 'ADRESSE CEDEX');
INSERT INTO gtyp6 VALUES ('7', 'POSTES AUX ARMEES');
INSERT INTO gtyp6 VALUES ('9', 'LIGNE VIDE');
-- nomenclature typcom (commune, voie)
INSERT INTO typcom VALUES ('N', 'Commune rurale');
INSERT INTO typcom VALUES ('R', 'Commune recensée');
-- nomenclature natvoiriv (voie)
INSERT INTO natvoiriv VALUES ('A', 'ensembles immobiliers');
INSERT INTO natvoiriv VALUES ('B', 'lieux-dits');
INSERT INTO natvoiriv VALUES ('C', 'lieux-dits');
INSERT INTO natvoiriv VALUES ('D', 'lieux-dits');
INSERT INTO natvoiriv VALUES ('E', 'lieux-dits');
INSERT INTO natvoiriv VALUES ('F', 'lieux-dits');
INSERT INTO natvoiriv VALUES ('G', 'lieux-dits');
INSERT INTO natvoiriv VALUES ('H', 'lieux-dits');
INSERT INTO natvoiriv VALUES ('I', 'lieux-dits');
INSERT INTO natvoiriv VALUES ('J', 'lieux-dits');
INSERT INTO natvoiriv VALUES ('K', 'lieux-dits');
INSERT INTO natvoiriv VALUES ('L', 'lieux-dits');
INSERT INTO natvoiriv VALUES ('M', 'lieux-dits');
INSERT INTO natvoiriv VALUES ('N', 'lieux-dits');
INSERT INTO natvoiriv VALUES ('O', 'lieux-dits');
INSERT INTO natvoiriv VALUES ('P', 'lieux-dits');
INSERT INTO natvoiriv VALUES ('Q', 'lieux-dits');
INSERT INTO natvoiriv VALUES ('R', 'lieux-dits');
INSERT INTO natvoiriv VALUES ('S', 'lieux-dits');
INSERT INTO natvoiriv VALUES ('T', 'lieux-dits');
INSERT INTO natvoiriv VALUES ('U', 'lieux-dits');
INSERT INTO natvoiriv VALUES ('V', 'lieux-dits');
INSERT INTO natvoiriv VALUES ('W', 'lieux-dits');
INSERT INTO natvoiriv VALUES ('X', 'pseudo-voies');
INSERT INTO natvoiriv VALUES ('Y', 'voies provisoires à annuler');
INSERT INTO natvoiriv VALUES ('Z', 'voies provisoires à annuler');
INSERT INTO natvoiriv VALUES ('0', 'voies');
INSERT INTO natvoiriv VALUES ('1', 'voies');
INSERT INTO natvoiriv VALUES ('2', 'voies');
INSERT INTO natvoiriv VALUES ('3', 'voies');
INSERT INTO natvoiriv VALUES ('4', 'voies');
INSERT INTO natvoiriv VALUES ('5', 'voies');
INSERT INTO natvoiriv VALUES ('6', 'voies');
INSERT INTO natvoiriv VALUES ('7', 'voies');
INSERT INTO natvoiriv VALUES ('8', 'voies');
INSERT INTO natvoiriv VALUES ('9', 'voies');
-- nomenclature carvoi (voie)
INSERT INTO carvoi VALUES ('1', 'voie privée');
INSERT INTO carvoi VALUES ('0', 'voie publique');
-- nomenclature annul (voie)
INSERT INTO annul VALUES ('O', 'voie annulée sans transfert');
INSERT INTO annul VALUES ('Q', 'voie annulée avec transfert');
-- nomenclature typvoi (voie)
INSERT INTO typvoi VALUES ('1', 'voie');
INSERT INTO typvoi VALUES ('2', 'ensemble immobilier');
INSERT INTO typvoi VALUES ('3', 'lieu-dit');
INSERT INTO typvoi VALUES ('4', 'pseudo-voie');
INSERT INTO typvoi VALUES ('5', 'voie provisoire');
-- nomenclature indldnbat (voie)
INSERT INTO indldnbat VALUES ('1', 'lieu-dit non bâti');
INSERT INTO indldnbat VALUES ('0', 'lieu-dit bâti');
-- nomenclatures geo
INSERT INTO geo_qupl VALUES ('01', 'Plan régulier établi avant le 20/03/1980');
INSERT INTO geo_qupl VALUES ('02', 'Plan non régulier');
INSERT INTO geo_qupl VALUES ('03', 'Plan de qualité P3 ou classe de précision [10 cm]');
INSERT INTO geo_qupl VALUES ('04', 'Plan de qualité P4 ou classe de précision [20 cm]');
INSERT INTO geo_qupl VALUES ('05', 'Plan de qualité P5 ou classe de précision [40 cm]');
INSERT INTO geo_copl VALUES ('01', 'ancien plan');
INSERT INTO geo_copl VALUES ('02', 'plan rénové par voie de mise à jour');
INSERT INTO geo_copl VALUES ('03', 'plan rénové par voie de renouvellement');
INSERT INTO geo_copl VALUES ('04', 'plan rénové par voie de réfection');
INSERT INTO geo_copl VALUES ('05', 'plan remanié');
INSERT INTO geo_copl VALUES ('06', 'plan obtenu par remembrement ou AFAF');
INSERT INTO geo_copl VALUES ('07', 'plan obtenu par exploitation de plans d''arpentage');
INSERT INTO geo_inp VALUES ('00','inconnu');
INSERT INTO geo_inp VALUES ('01','numérisation manuelle');
INSERT INTO geo_inp VALUES ('02','numérisation par scanner');
INSERT INTO geo_inp VALUES ('03','incorporation directe sans numérisation préalable');
INSERT INTO geo_indp VALUES ('01', 'parcelle figurée au plan');
INSERT INTO geo_indp VALUES ('02', 'parcelle non figurée au plan');
INSERT INTO geo_dur VALUES ('01', 'bâti dur');
INSERT INTO geo_dur VALUES ('02', 'bâti léger');
INSERT INTO geo_can VALUES ('00', 'Inconnu');
INSERT INTO geo_can VALUES ('01', 'IGN');
INSERT INTO geo_can VALUES ('02', 'Cadastre');
INSERT INTO geo_can VALUES ('03', 'Commune');
INSERT INTO geo_can VALUES ('04', 'Équipement');
INSERT INTO geo_can VALUES ('05', 'Département');
INSERT INTO geo_can VALUES ('06', 'SNCF');
INSERT INTO geo_can VALUES ('07', 'RATP');
INSERT INTO geo_can VALUES ('08', 'EDF');
INSERT INTO geo_can VALUES ('09', 'GDF');
INSERT INTO geo_can VALUES ('10', 'Collectivité territoriale');
INSERT INTO geo_can VALUES ('98', 'Divers maîtres d''ouvrage');
INSERT INTO geo_ppln VALUES ('00', 'inconnu');
INSERT INTO geo_ppln VALUES ('01', 'canevas géodésique du 1er ordre');
INSERT INTO geo_ppln VALUES ('02', 'canevas géodésique du 2ème ordre');
INSERT INTO geo_ppln VALUES ('03', 'canevas géodésique du 3ème ordre');
INSERT INTO geo_ppln VALUES ('04', 'canevas géodésique du 4ème ordre');
INSERT INTO geo_ppln VALUES ('05', 'canevas complémentaire (5ème ordre)');
INSERT INTO geo_ppln VALUES ('06', 'canevas d''ensemble ou de stéréopréparation de précision');
INSERT INTO geo_ppln VALUES ('07', 'canevas d''ensemble ou de stéréopréparation ordinaire, y compris triangulation < 1980');
INSERT INTO geo_ppln VALUES ('08', 'canevas polygonal de précision');
INSERT INTO geo_ppln VALUES ('09', 'canevas polygonal ordinaire ou antérieur à 1980');
INSERT INTO geo_ppln VALUES ('10', 'aérocanevas ou charpente photogrammétrique');
INSERT INTO geo_ppln VALUES ('11', 'point de charpente');
INSERT INTO geo_ppln VALUES ('12', 'localisation planimétrique d''un point de nivellement');
INSERT INTO geo_ppln VALUES ('20', 'canevas pérenne ou de précision (depuis 2001)');
INSERT INTO geo_ppln VALUES ('21', 'canevas ordinaire ou préalable à AFAF ou de stéréopréparation pour une PdV inférieure au 1/4000 (depuis 2001)');
INSERT INTO geo_ppln VALUES ('22', 'canevas de stéréopréparation pour une PdV au 1/2500 (depuis 2001)');
INSERT INTO geo_ppln VALUES ('23', 'canevas d''appui pour géoréférencement (depuis 2001)');
INSERT INTO geo_ppln VALUES ('24', 'canevas géodésique RGF93-RRF');
INSERT INTO geo_ppln VALUES ('25', 'canevas géodésique RGF93-RBF');
INSERT INTO geo_ppln VALUES ('26', 'canevas géodésique RGF93-RDF');
INSERT INTO geo_ppln VALUES ('27', 'canevas géodésique WGS84-UTM Nord fuseau 20 (Guadeloupe et Martinique  : 971 et 972)');
INSERT INTO geo_ppln VALUES ('28', 'canevas géodésique RGF95-UTM Nord fuseau 22 (Guyane : 973)');
INSERT INTO geo_ppln VALUES ('29', 'canevas géodésique RGR92-UTM Sud fuseau 40 (Réunion : 974)');
INSERT INTO geo_ppln VALUES ('30', 'canevas géodésique RGM04-UTM Sud fuseau 38 (Mayotte : 976)');
INSERT INTO geo_ppln VALUES ('98', 'point de levé cadastral');
INSERT INTO geo_palt VALUES ('00', 'inconnu');
INSERT INTO geo_palt VALUES ('01', 'canevas de nivellement direct de haute précision');
INSERT INTO geo_palt VALUES ('02', 'canevas de nivellement direct de précision');
INSERT INTO geo_palt VALUES ('03', 'canevas de nivellement direct ordinaire');
INSERT INTO geo_palt VALUES ('04', 'canevas de nivellement indirect géodésique');
INSERT INTO geo_palt VALUES ('05', 'canevas de nivellement indirect trigonométrique');
INSERT INTO geo_palt VALUES ('06', 'cote altimétrique obtenue par photogrammétrie');
INSERT INTO geo_palt VALUES ('98', 'autre canevas de nivellement');
INSERT INTO geo_map VALUES ('00', 'inconnu');
INSERT INTO geo_map VALUES ('01', 'non matérialisé');
INSERT INTO geo_map VALUES ('02', 'matérialisé');
INSERT INTO geo_map VALUES ('03', 'rivet ou boulon');
INSERT INTO geo_map VALUES ('04', 'croix gravée');
INSERT INTO geo_map VALUES ('06', 'pylône');
INSERT INTO geo_map VALUES ('07', 'borne');
INSERT INTO geo_map VALUES ('98', 'autre point net et stable, naturel ou artificiel');
INSERT INTO geo_sym VALUES ('12', 'calvaire');
INSERT INTO geo_sym VALUES ('13', 'texture transparente');
INSERT INTO geo_sym VALUES ('14', 'symbole d''église');
INSERT INTO geo_sym VALUES ('15', 'symbole de mosquée');
INSERT INTO geo_sym VALUES ('16', 'symbole de synagogue');
INSERT INTO geo_sym VALUES ('17', 'limite d''Etat');
INSERT INTO geo_sym VALUES ('18', 'limite de département');
INSERT INTO geo_sym VALUES ('19', 'amorce de limite de commune');
INSERT INTO geo_sym VALUES ('21', 'chemin');
INSERT INTO geo_sym VALUES ('22', 'amorce de voie');
INSERT INTO geo_sym VALUES ('23', 'trottoirs et sentiers');
INSERT INTO geo_sym VALUES ('24', 'gazoduc ou oléoduc');
INSERT INTO geo_sym VALUES ('25', 'aqueduc');
INSERT INTO geo_sym VALUES ('26', 'téléphérique');
INSERT INTO geo_sym VALUES ('27', 'ligne de transport de force');
INSERT INTO geo_sym VALUES ('29', 'rail de chemin de fer');
INSERT INTO geo_sym VALUES ('30', 'flèche de cours d''eau');
INSERT INTO geo_sym VALUES ('31', 'flèche de rattachement d''un numéro deparcelle ou de la référence d''un bâtiment sur le domaine non cadastré');
INSERT INTO geo_sym VALUES ('32', 'limite surfacique ne formant pas parcelle');
INSERT INTO geo_sym VALUES ('33', 'parapet de pont');
INSERT INTO geo_sym VALUES ('34', 'étang, lac, mare');
INSERT INTO geo_sym VALUES ('37', 'tunnel');
INSERT INTO geo_sym VALUES ('39', 'mur mitoyen');
INSERT INTO geo_sym VALUES ('40', 'mur non mitoyen');
INSERT INTO geo_sym VALUES ('41', 'fossé mitoyen');
INSERT INTO geo_sym VALUES ('42', 'fossé non mitoyen');
INSERT INTO geo_sym VALUES ('43', 'clôture mitoyenne');
INSERT INTO geo_sym VALUES ('44', 'clôture non mitoyenne');
INSERT INTO geo_sym VALUES ('45', 'haie mitoyenne');
INSERT INTO geo_sym VALUES ('46', 'haie non mitoyenne');
INSERT INTO geo_sym VALUES ('47', 'halte');
INSERT INTO geo_sym VALUES ('48', 'arrêt');
INSERT INTO geo_sym VALUES ('49', 'station');
INSERT INTO geo_sym VALUES ('50', 'pylône');
INSERT INTO geo_sym VALUES ('51', 'cimetière chrétien');
INSERT INTO geo_sym VALUES ('52', 'cimetière israélite');
INSERT INTO geo_sym VALUES ('53', 'cimetière musulman');
INSERT INTO geo_sym VALUES ('62', 'terrain de sports, petits ruisseaux');
INSERT INTO geo_sym VALUES ('63', 'puits');
INSERT INTO geo_sym VALUES ('64', 'parking, terrasse, surplomb');
INSERT INTO geo_sym VALUES ('65', 'piscine');
INSERT INTO geo_sym VALUES ('71', 'point géodésique borné');
INSERT INTO geo_sym VALUES ('72', 'point géodésique non borné');
INSERT INTO geo_sym VALUES ('73', 'point borné de canevas cadastral ordinaire/préalable à AFAF/appui prise de vues permettant confection plan de classe de précision 20cm');
INSERT INTO geo_sym VALUES ('74', 'point borné de canevas pérenne ou de précision');
INSERT INTO geo_sym VALUES ('75', 'point borné de canevas d''appui d''une prise de vues permettant la confection d''un plan de classe de précision 10cm');
INSERT INTO geo_sym VALUES ('76', 'point borné d''appui de géoréférencement');
INSERT INTO geo_sym VALUES ('77', 'repère NGF');
INSERT INTO geo_sym VALUES ('78', 'borne du NGF');
INSERT INTO geo_sym VALUES ('79', 'nivellement MRL');
INSERT INTO geo_sym VALUES ('80', 'autre repère de nivellement');
INSERT INTO geo_sym VALUES ('81', 'borne limite de commune');
INSERT INTO geo_sym VALUES ('98', 'objet ponctuel/linéaire divers');

-- nomenclatures Forme juridique (depuis 2013) : dformjur
INSERT INTO dformjur VALUES ('1100', Null, 'Artisan-commerçant');
INSERT INTO dformjur VALUES ('1200', Null, 'Commerçant');
INSERT INTO dformjur VALUES ('1300', Null, 'Artisan');
INSERT INTO dformjur VALUES ('1400', Null, 'Officier public ou ministériel');
INSERT INTO dformjur VALUES ('1500', Null, 'Profession libérale');
INSERT INTO dformjur VALUES ('1600', Null, 'Exploitant agricole');
INSERT INTO dformjur VALUES ('1700', Null, 'Agent commercial');
INSERT INTO dformjur VALUES ('1800', Null, 'Associé gérant de Société');
INSERT INTO dformjur VALUES ('1900', Null, '(Autre) Personne physique');
INSERT INTO dformjur VALUES ('2110', Null, 'Indivision entre personnes physiques');
INSERT INTO dformjur VALUES ('2120', Null, 'Indivision avec personne morale');
INSERT INTO dformjur VALUES ('2210', 'STE', 'Société créée de fait entre personnes physiques');
INSERT INTO dformjur VALUES ('2220', 'STE', 'Société créée de fait avec personne morale');
INSERT INTO dformjur VALUES ('2310', 'STE', 'Société en participation entre personnes physiques');
INSERT INTO dformjur VALUES ('2320', 'STE', 'Société en participation avec personne morale');
INSERT INTO dformjur VALUES ('2385', 'STE', 'Société en participation de professions libérales');
INSERT INTO dformjur VALUES ('2400', Null, 'Fiducie');
INSERT INTO dformjur VALUES ('2700', 'PAR', 'Paroisse hors zone concordataire');
INSERT INTO dformjur VALUES ('2900', Null, 'Autre groupement de droit privé non doté de la personnalité morale');
INSERT INTO dformjur VALUES ('3110', Null, 'Représentation ou agence commerciale d''état ou organisme public étranger immatriculé au RCS');
INSERT INTO dformjur VALUES ('3120', 'STE', 'Société commerciale étrangère immatriculée au RCS');
INSERT INTO dformjur VALUES ('3205', Null, 'Organisation internationale');
INSERT INTO dformjur VALUES ('3210', Null, 'État, collectivité ou établissement public étranger');
INSERT INTO dformjur VALUES ('3220', 'STE', 'Société étrangère non immatriculée au RCS');
INSERT INTO dformjur VALUES ('3290', Null, 'Autre personne morale de droit étranger');
INSERT INTO dformjur VALUES ('4110', 'EPIC', 'Établissement public national à caractère industriel ou commercial doté d''un comptable public');
INSERT INTO dformjur VALUES ('4120', 'EPIC', 'Établissement public national à caractère industriel ou commercial non doté d''un comptable public');
INSERT INTO dformjur VALUES ('4130', Null, 'Exploitant public');
INSERT INTO dformjur VALUES ('4140', 'EPIC', 'Établissement public local à caractère industriel ou commercial');
INSERT INTO dformjur VALUES ('4150', 'REGI', 'Régie d''une collectivité locale à caractère industriel ou commercial');
INSERT INTO dformjur VALUES ('4160', 'BDF', 'Institution Banque de France');
INSERT INTO dformjur VALUES ('5191', 'SCCP', 'Société de caution mutuelle');
INSERT INTO dformjur VALUES ('5192', 'SCCP', 'Société coopérative de banque populaire');
INSERT INTO dformjur VALUES ('5193', 'SCCP', 'Caisse de crédit maritime mutuel');
INSERT INTO dformjur VALUES ('5194', 'SCCP', 'Caisse (fédérale) de crédit mutuel');
INSERT INTO dformjur VALUES ('5195', 'SCCP', 'Association coopérative inscrite (droit local Alsace Moselle)');
INSERT INTO dformjur VALUES ('5196', 'SCCP', 'Caisse d''épargne et de prévoyance à forme coopérative');
INSERT INTO dformjur VALUES ('5202', 'SNC', 'Société en nom collectif');
INSERT INTO dformjur VALUES ('5203', 'SNC', 'Société en nom collectif coopérative');
INSERT INTO dformjur VALUES ('5306', 'SCOM', 'Société en commandite simple');
INSERT INTO dformjur VALUES ('5307', 'SCOM', 'Société en commandite simple coopérative');
INSERT INTO dformjur VALUES ('5308', 'SCOM', 'Société en commandite par actions');
INSERT INTO dformjur VALUES ('5309', 'SCOM', 'Société en commandite par actions coopérative');
INSERT INTO dformjur VALUES ('5370', 'SCOM', 'Société de participations financières de profession libérale société en commandite par action');
INSERT INTO dformjur VALUES ('5385', 'SCOM', 'Société d''exercice libéral en commandite par actions');
INSERT INTO dformjur VALUES ('5410', 'SARL', 'SARL nationale');
INSERT INTO dformjur VALUES ('5415', 'SARL', 'SARL d''économie mixte');
INSERT INTO dformjur VALUES ('5422', 'SARL', 'SARL immobilière pour le commerce et l''industrie (SICOMI)');
INSERT INTO dformjur VALUES ('5426', 'SARL', 'SARL immobilière de gestion');
INSERT INTO dformjur VALUES ('5430', 'SARL', 'SARL d''aménagement foncier et d''équipement rural (SAFER)');
INSERT INTO dformjur VALUES ('5431', 'SARL', 'SARL mixte d''intérêt agricole (SMIA)');
INSERT INTO dformjur VALUES ('5432', 'SARL', 'SARL d''intérêt collectif agricole (SICA)');
INSERT INTO dformjur VALUES ('5442', 'SARL', 'SARL d''attribution');
INSERT INTO dformjur VALUES ('5443', 'SARL', 'SARL coopérative de construction');
INSERT INTO dformjur VALUES ('5451', 'SARL', 'SARL coopérative de consommation');
INSERT INTO dformjur VALUES ('5453', 'SARL', 'SARL coopérative artisanale');
INSERT INTO dformjur VALUES ('5454', 'SARL', 'SARL coopérative d''intérêt maritime');
INSERT INTO dformjur VALUES ('5455', 'SARL', 'SARL coopérative de transport');
INSERT INTO dformjur VALUES ('5458', 'SARL', 'SARL coopérative ouvrière de production et de crédit (SCOP)');
INSERT INTO dformjur VALUES ('5459', 'SARL', 'SARL union de sociétés coopératives');
INSERT INTO dformjur VALUES ('5460', 'SARL', 'Autre SARL coopérative');
INSERT INTO dformjur VALUES ('5470', 'SARL', 'Société de participations financières de profession libérale société à responsabilité limitée');
INSERT INTO dformjur VALUES ('5485', 'SLRL', 'Société d''exercice libéral à responsabilité limitée');
INSERT INTO dformjur VALUES ('5498', 'EURL', 'SARL unipersonnelle');
INSERT INTO dformjur VALUES ('5499', 'SARL', 'Société à responsabilité limitée (sans autre indication)');
INSERT INTO dformjur VALUES ('5505', 'SA', 'SA à participation ouvrière à conseil d''administration');
INSERT INTO dformjur VALUES ('5510', 'SA', 'SA nationale à conseil d''administration');
INSERT INTO dformjur VALUES ('5515', 'SEM', 'SA d''économie mixte à conseil d''administration');
INSERT INTO dformjur VALUES ('5520', 'STE', 'Fond à forme sociétale à conseil d’administration');
INSERT INTO dformjur VALUES ('5522', 'STE', 'SA immobilière pour le commerce et l''industrie (SICOMI) à conseil d''administration');
INSERT INTO dformjur VALUES ('5525', 'SA', 'SA immobilière d''investissement à conseil d''administration');
INSERT INTO dformjur VALUES ('5530', Null, 'SA d''aménagement foncier et d''équipement rural (SAFER) à conseil d''administration');
INSERT INTO dformjur VALUES ('5531', 'SA', 'Société anonyme mixte d''intérêt agricole (SMIA) à conseil d''administration');
INSERT INTO dformjur VALUES ('5532', 'SICA', 'SA d''intérêt collectif agricole (SICA) à conseil d''administration');
INSERT INTO dformjur VALUES ('5542', 'SA', 'SA d''attribution à conseil d''administration');
INSERT INTO dformjur VALUES ('5543', 'SA', 'SA coopérative de construction à conseil d''administration');
INSERT INTO dformjur VALUES ('5546', 'SA', 'SA de HLM à conseil d''administration');
INSERT INTO dformjur VALUES ('5547', 'SA', 'SA coopérative de production de HLM à conseil d''administration');
INSERT INTO dformjur VALUES ('5548', 'SA', 'SA de crédit immobilier à conseil d''administration');
INSERT INTO dformjur VALUES ('5551', 'SA', 'SA coopérative de consommation à conseil d''administration');
INSERT INTO dformjur VALUES ('5552', 'SA', 'SA coopérative de commerçants-détaillants à conseil d''administration');
INSERT INTO dformjur VALUES ('5553', 'SA', 'SA coopérative artisanale à conseil d''administration');
INSERT INTO dformjur VALUES ('5554', 'SA', 'SA coopérative (d''intérêt) maritime à conseil d''administration');
INSERT INTO dformjur VALUES ('5555', 'SA', 'SA coopérative de transport à conseil d''administration');
INSERT INTO dformjur VALUES ('5558', 'SCOP', 'SA coopérative ouvrière de production et de crédit (SCOP) à conseil d''administration');
INSERT INTO dformjur VALUES ('5559', 'SA', 'SA union de sociétés coopératives à conseil d''administration');
INSERT INTO dformjur VALUES ('5560', 'SA', 'Autre SA coopérative à conseil d''administration');
INSERT INTO dformjur VALUES ('5570', 'SA', 'Société de participations financières de profession libérale société anonyme à conseil d’administration');
INSERT INTO dformjur VALUES ('5585', 'STE', 'Société d''exercice libéral à forme anonyme à conseil d''administration');
INSERT INTO dformjur VALUES ('5599', 'SA', 'SA à conseil d''administration (s.a.i.)');
INSERT INTO dformjur VALUES ('5605', 'SA', 'SA à participation ouvrière à directoire');
INSERT INTO dformjur VALUES ('5610', 'SA', 'SA nationale à directoire');
INSERT INTO dformjur VALUES ('5615', 'SA', 'SA d''économie mixte à directoire');
INSERT INTO dformjur VALUES ('5620', 'STE', 'Fond à forme sociétale à directoire');
INSERT INTO dformjur VALUES ('5622', 'STE', 'SA immobilière pour le commerce et l''industrie (SICOMI) à directoire');
INSERT INTO dformjur VALUES ('5625', 'STE', 'SA immobilière d''investissement à directoire');
INSERT INTO dformjur VALUES ('5630', Null, 'Safer anonyme à directoire');
INSERT INTO dformjur VALUES ('5631', 'SA', 'SA mixte d''intérêt agricole (SMIA)');
INSERT INTO dformjur VALUES ('5632', 'SA', 'SA d''intérêt collectif agricole (SICA)');
INSERT INTO dformjur VALUES ('5642', 'SA', 'SA d''attribution à directoire');
INSERT INTO dformjur VALUES ('5643', 'SA', 'SA coopérative de construction à directoire');
INSERT INTO dformjur VALUES ('5646', 'SA', 'SA de HLM à directoire');
INSERT INTO dformjur VALUES ('5647', 'STE', 'Société coopérative de production de HLM anonyme à directoire');
INSERT INTO dformjur VALUES ('5648', 'SA', 'SA de crédit immobilier à directoire');
INSERT INTO dformjur VALUES ('5651', 'SA', 'SA coopérative de consommation à directoire');
INSERT INTO dformjur VALUES ('5652', 'SA', 'SA coopérative de commerçants-détaillants à directoire');
INSERT INTO dformjur VALUES ('5653', 'SA', 'SA coopérative artisanale à directoire');
INSERT INTO dformjur VALUES ('5654', 'SA', 'SA coopérative d''intérêt maritime à directoire');
INSERT INTO dformjur VALUES ('5655', 'SA', 'SA coopérative de transport à directoire');
INSERT INTO dformjur VALUES ('5658', 'SCOP', 'SA coopérative ouvrière de production et de crédit (SCOP) à directoire');
INSERT INTO dformjur VALUES ('5659', 'SA', 'SA union de sociétés coopératives à directoire');
INSERT INTO dformjur VALUES ('5660', 'SA', 'Autre SA coopérative à directoire');
INSERT INTO dformjur VALUES ('5670', 'SA', 'Société de participations financières de profession libérale société anonyme à directoire');
INSERT INTO dformjur VALUES ('5685', 'SA', 'Société d''exercice libéral à forme anonyme à directoire');
INSERT INTO dformjur VALUES ('5699', 'SA', 'SA à directoire (s.a.i.)');
INSERT INTO dformjur VALUES ('5710', 'SAS', 'SAS, société par actions simplifiée');
INSERT INTO dformjur VALUES ('5720', 'SAS', 'Société par actions simplifiée à associé unique ou société par actions simplifiée unipersonnelle');
INSERT INTO dformjur VALUES ('5770', 'SAS', 'Société de participations financières de profession libérale société par actions simplifiée');
INSERT INTO dformjur VALUES ('5785', 'SAS', 'Société d''exercice libéral par action simplifiée');
INSERT INTO dformjur VALUES ('5800', 'SE', 'Société européenne');
INSERT INTO dformjur VALUES ('6100', 'CEP', 'Caisse d''Épargne et de Prévoyance');
INSERT INTO dformjur VALUES ('6210', 'GIE', 'Groupement européen d''intérêt économique (GEIE)');
INSERT INTO dformjur VALUES ('6220', 'GIE', 'Groupement d''intérêt économique (GIE)');
INSERT INTO dformjur VALUES ('6316', 'CUMA', 'Coopérative d''utilisation de matériel agricole en commun (CUMA)');
INSERT INTO dformjur VALUES ('6317', 'SCA', 'Société coopérative agricole');
INSERT INTO dformjur VALUES ('6318', 'SCA', 'Union de sociétés coopératives agricoles');
INSERT INTO dformjur VALUES ('6411', 'SAM', 'Société d''assurance à forme mutuelle');
INSERT INTO dformjur VALUES ('6412', 'SAM', 'Société mutuelle d''assurance');
INSERT INTO dformjur VALUES ('6413', 'SAM', 'Union de sociétés mutuelles d''assurances');
INSERT INTO dformjur VALUES ('6414', 'SAM', 'Autre société non commerciale d''assurance');
INSERT INTO dformjur VALUES ('6511', 'STE', 'Société interprofessionnelle de soins ambulatoires');
INSERT INTO dformjur VALUES ('6521', 'SCPI', 'Société civile de placement collectif immobilier (SCPI)');
INSERT INTO dformjur VALUES ('6532', 'SICA', 'Société civile d''intérêt collectif agricole (SICA)');
INSERT INTO dformjur VALUES ('6533', 'GAEC', 'Groupement agricole d''exploitation en commun (GAEC)');
INSERT INTO dformjur VALUES ('6534', 'GFA', 'Groupement foncier agricole');
INSERT INTO dformjur VALUES ('6535', 'GAF', 'Groupement agricole foncier');
INSERT INTO dformjur VALUES ('6536', 'GFO', 'Groupement forestier');
INSERT INTO dformjur VALUES ('6537', 'GPAS', 'Groupement pastoral');
INSERT INTO dformjur VALUES ('6538', 'GFR', 'Groupement foncier et rural');
INSERT INTO dformjur VALUES ('6539', 'STE', 'Société civile foncière');
INSERT INTO dformjur VALUES ('6540', 'SCI', 'Société civile immobilière');
INSERT INTO dformjur VALUES ('6541', 'SCI', 'Société civile immobilière de construction-vente');
INSERT INTO dformjur VALUES ('6542', 'SC', 'Société civile d''attribution');
INSERT INTO dformjur VALUES ('6543', 'SC', 'Société civile coopérative de construction');
INSERT INTO dformjur VALUES ('6544', 'SCI', 'Société civile immobilière d'' accession progressive à la propriété');
INSERT INTO dformjur VALUES ('6551', 'SC', 'Société civile coopérative de consommation');
INSERT INTO dformjur VALUES ('6554', 'SC', 'Société civile coopérative d''intérêt maritime');
INSERT INTO dformjur VALUES ('6558', 'SC', 'Société civile coopérative entre médecins');
INSERT INTO dformjur VALUES ('6560', 'SC', 'Autre société civile coopérative');
INSERT INTO dformjur VALUES ('6561', 'SCP', 'SCP d''avocats');
INSERT INTO dformjur VALUES ('6562', 'SCP', 'SCP d''avocats aux conseils');
INSERT INTO dformjur VALUES ('6563', 'SCP', 'SCP d''avoués d''appel');
INSERT INTO dformjur VALUES ('6564', 'SCP', 'SCP d''huissiers');
INSERT INTO dformjur VALUES ('6565', 'SCP', 'SCP de notaires');
INSERT INTO dformjur VALUES ('6566', 'SCP', 'SCP de commissaires-priseurs');
INSERT INTO dformjur VALUES ('6567', 'SCP', 'SCP de greffiers de tribunal de commerce');
INSERT INTO dformjur VALUES ('6568', 'SCP', 'SCP de conseils juridiques');
INSERT INTO dformjur VALUES ('6569', 'SCP', 'SCP de commissaires aux comptes');
INSERT INTO dformjur VALUES ('6571', 'SCP', 'SCP de médecins');
INSERT INTO dformjur VALUES ('6572', 'SCP', 'SCP de dentistes');
INSERT INTO dformjur VALUES ('6573', 'SCP', 'SCP d''infirmiers');
INSERT INTO dformjur VALUES ('6574', 'SCP', 'SCP de masseurs-kinésithérapeutes');
INSERT INTO dformjur VALUES ('6575', 'SCP', 'SCP de directeurs de laboratoire d''analyse médicale');
INSERT INTO dformjur VALUES ('6576', 'SCP', 'SCP de vétérinaires');
INSERT INTO dformjur VALUES ('6577', 'SCP', 'SCP de géomètres experts');
INSERT INTO dformjur VALUES ('6578', 'SCP', 'SCP d''architectes');
INSERT INTO dformjur VALUES ('6585', 'SC', 'Autre société civile professionnelle');
INSERT INTO dformjur VALUES ('6588', 'SCM', 'Société civile laitière');
INSERT INTO dformjur VALUES ('6589', 'CCM', 'Société civile de moyens');
INSERT INTO dformjur VALUES ('6595', 'CCAM', 'Caisse locale de crédit mutuel');
INSERT INTO dformjur VALUES ('6596', 'SCEA', 'Caisse de crédit agricole mutuel');
INSERT INTO dformjur VALUES ('6597', 'EARL', 'Société civile d''exploitation agricole');
INSERT INTO dformjur VALUES ('6598', 'SC', 'Exploitation agricole à responsabilité limitée');
INSERT INTO dformjur VALUES ('6599', Null, 'Autre société civile');
INSERT INTO dformjur VALUES ('6901', Null, 'Autre personne de droit privé inscrite au registre du commerce et des sociétés');
INSERT INTO dformjur VALUES ('7111', Null, 'Autorité constitutionnelle');
INSERT INTO dformjur VALUES ('7112', 'ETAT', 'Autorité administrative ou publique indépendante');
INSERT INTO dformjur VALUES ('7113', 'ETAT', 'Ministère');
INSERT INTO dformjur VALUES ('7120', 'ETAT', 'Service central d''un ministère');
INSERT INTO dformjur VALUES ('7150', 'ETAT', 'Service du ministère de la Défense');
INSERT INTO dformjur VALUES ('7160', 'ETAT', 'Service déconcentré à compétence nationale d''un ministère (horsDéfense)');
INSERT INTO dformjur VALUES ('7171', 'ETAT', 'Service déconcentré de l''État à compétence (inter) régionale');
INSERT INTO dformjur VALUES ('7172', 'ETAT', 'Service déconcentré de l''État à compétence (inter) départementale');
INSERT INTO dformjur VALUES ('7179', 'ETAT', '(Autre) Service déconcentré de l''État à compétence territoriale');
INSERT INTO dformjur VALUES ('7190', Null, 'Ecole nationale non dotée de la personnalité morale');
INSERT INTO dformjur VALUES ('7210', 'COM', 'Commune et commune nouvelle');
INSERT INTO dformjur VALUES ('7220', 'DEPT', 'Département');
INSERT INTO dformjur VALUES ('7225', 'CTOM', 'Territoire d''Outre-mer');
INSERT INTO dformjur VALUES ('7229', 'COLL', '(Autre) Collectivité territoriale');
INSERT INTO dformjur VALUES ('7230', 'COLL', 'Région');
INSERT INTO dformjur VALUES ('7312', Null, 'Commune associée et commune déléguée');
INSERT INTO dformjur VALUES ('7313', Null, 'Section de commune');
INSERT INTO dformjur VALUES ('7314', Null, 'Ensemble urbain');
INSERT INTO dformjur VALUES ('7321', 'ASS', 'Association syndicale autorisée');
INSERT INTO dformjur VALUES ('7322', 'AFU', 'Association foncière urbaine');
INSERT INTO dformjur VALUES ('7323', 'AFR', 'Association foncière de remembrement');
INSERT INTO dformjur VALUES ('7331', 'EP', 'Établissement public local d''enseignement');
INSERT INTO dformjur VALUES ('7340', Null, 'Pôle métropolitain');
INSERT INTO dformjur VALUES ('7341', Null, 'Secteur de commune');
INSERT INTO dformjur VALUES ('7342', 'DISU', 'District urbain');
INSERT INTO dformjur VALUES ('7343', 'COMU', 'Communauté urbaine');
INSERT INTO dformjur VALUES ('7344', Null, 'Métropole');
INSERT INTO dformjur VALUES ('7345', 'SIVO', 'Syndicat intercommunal à vocation multiple (SIVOM)');
INSERT INTO dformjur VALUES ('7346', 'CCOM', 'Communauté de communes');
INSERT INTO dformjur VALUES ('7347', 'COVI', 'Communauté de villes');
INSERT INTO dformjur VALUES ('7348', 'COAG', 'Communauté d''agglomération');
INSERT INTO dformjur VALUES ('7349', Null, 'Autre établissement public local de coopération non spécialisé ou entente');
INSERT INTO dformjur VALUES ('7351', Null, 'Institution interdépartementale ou entente');
INSERT INTO dformjur VALUES ('7352', Null, 'Institution interrégionale ou entente');
INSERT INTO dformjur VALUES ('7353', 'SIVU', 'Syndicat intercommunal à vocation unique (SIVU)');
INSERT INTO dformjur VALUES ('7354', 'SYMC', 'Syndicat mixte fermé');
INSERT INTO dformjur VALUES ('7355', 'SYMI', 'Syndicat mixte ouvert');
INSERT INTO dformjur VALUES ('7356', Null, 'Commission syndicale pour la gestion des biens indivis descommunes');
INSERT INTO dformjur VALUES ('7357', 'PETR', 'Pôle d’équilibre territorial');
INSERT INTO dformjur VALUES ('7361', 'CCAS', 'Centre communal d''action sociale');
INSERT INTO dformjur VALUES ('7362', Null, 'Caisse des écoles');
INSERT INTO dformjur VALUES ('7363', 'CCMU', 'Caisse de crédit municipal');
INSERT INTO dformjur VALUES ('7364', Null, 'Établissement d''hospitalisation');
INSERT INTO dformjur VALUES ('7365', Null, 'Syndicat inter hospitalier');
INSERT INTO dformjur VALUES ('7366', Null, 'Établissement public local social et médico-social');
INSERT INTO dformjur VALUES ('7367', 'CIAS', 'Centre intercommunal d’action social');
INSERT INTO dformjur VALUES ('7371', 'OHLM', 'Office public d''habitation à loyer modéré (OPHLM)');
INSERT INTO dformjur VALUES ('7372', 'SDIS', 'Service départemental d''incendie');
INSERT INTO dformjur VALUES ('7373', 'EP', 'Établissement public local culturel');
INSERT INTO dformjur VALUES ('7378', 'EPA', 'Régie d''une collectivité locale à caractère administratif');
INSERT INTO dformjur VALUES ('7379', 'EPA', '(Autre) Établissement public administratif local');
INSERT INTO dformjur VALUES ('7381', 'EPA', 'Organisme consulaire');
INSERT INTO dformjur VALUES ('7382', 'EPA', 'Établissement public national ayant fonction d''administration centrale');
INSERT INTO dformjur VALUES ('7383', 'EPA', 'Établissement public national à caractère scientifique culturel et professionnel');
INSERT INTO dformjur VALUES ('7384', 'EPA', 'Autre établissement public national d''enseignement');
INSERT INTO dformjur VALUES ('7385', 'EPA', 'Autre établissement public national administratif à compétence territoriale limitée');
INSERT INTO dformjur VALUES ('7389', 'EPA', 'Établissement public national à caractère administratif');
INSERT INTO dformjur VALUES ('7410', 'GIP', 'Groupement d''intérêt public (GIP)');
INSERT INTO dformjur VALUES ('7430', 'EPA', 'Établissement public des cultes d''Alsace-Lorraine');
INSERT INTO dformjur VALUES ('7450', 'EPA', 'Etablissement public administratif, cercle et foyer dans les armées');
INSERT INTO dformjur VALUES ('7470', 'GCS', 'Groupement de coopération sanitaire à gestion publique');
INSERT INTO dformjur VALUES ('7490', Null, 'Autre personne morale de droit administratif');
INSERT INTO dformjur VALUES ('7510', Null, 'Service d''une collectivité locale à comptabilité distincte');
INSERT INTO dformjur VALUES ('7520', Null, 'Régie d''une collectivité locale non dotée de la personnalité morale');
INSERT INTO dformjur VALUES ('8110', 'SSRG', 'Régime général de la Sécurité Sociale');
INSERT INTO dformjur VALUES ('8120', 'SSRS', 'Régime spécial de Sécurité Sociale');
INSERT INTO dformjur VALUES ('8130', 'IRC', 'Institution de retraite complémentaire');
INSERT INTO dformjur VALUES ('8140', 'MSA', 'Mutualité sociale agricole');
INSERT INTO dformjur VALUES ('8150', Null, 'Régime maladie des non-salariés non agricoles');
INSERT INTO dformjur VALUES ('8160', Null, 'Régime vieillesse ne dépendant pas du régime général de laSécurité Sociale');
INSERT INTO dformjur VALUES ('8170', Null, 'Régime d''assurance chômage');
INSERT INTO dformjur VALUES ('8190', Null, 'Autre régime de prévoyance sociale');
INSERT INTO dformjur VALUES ('8210', 'MUT', 'Mutuelle');
INSERT INTO dformjur VALUES ('8250', 'MUT', 'Assurance mutuelle agricole');
INSERT INTO dformjur VALUES ('8290', 'MUT', 'Autre organisme mutualiste');
INSERT INTO dformjur VALUES ('8310', 'COME', 'Comité central d''entreprise');
INSERT INTO dformjur VALUES ('8311', 'COME', 'Comité d''établissement');
INSERT INTO dformjur VALUES ('8410', 'OPRO', 'Syndicat de salariés');
INSERT INTO dformjur VALUES ('8420', 'OPRO', 'Syndicat patronal');
INSERT INTO dformjur VALUES ('8450', 'OPRO', 'Ordre professionnel ou assimilé');
INSERT INTO dformjur VALUES ('8470', 'OPRO', 'Centre technique industriel ou comité professionnel du développement économique');
INSERT INTO dformjur VALUES ('8490', 'OPRO', 'Autre organisme professionnel');
INSERT INTO dformjur VALUES ('8510', 'IP', 'Institution de prévoyance');
INSERT INTO dformjur VALUES ('8520', 'IRS', 'Institution de retraite supplémentaire');
INSERT INTO dformjur VALUES ('9110', 'SYCO', 'Syndicat de copropriété');
INSERT INTO dformjur VALUES ('9150', 'ASS', 'Association syndicale libre');
INSERT INTO dformjur VALUES ('9210', 'ASS', 'Association non déclarée');
INSERT INTO dformjur VALUES ('9220', 'ASS', 'Association déclarée');
INSERT INTO dformjur VALUES ('9221', 'ASS', 'Association déclarée d''insertion par l''économique');
INSERT INTO dformjur VALUES ('9222', 'ASS', 'Association intermédiaire');
INSERT INTO dformjur VALUES ('9223', 'ASS', 'Groupement d''employeurs');
INSERT INTO dformjur VALUES ('9224', 'ASS', 'Association d''avocats à responsabilité professionnelle individuelle');
INSERT INTO dformjur VALUES ('9230', 'ASS', 'Association déclarée, reconnue d''utilité publique');
INSERT INTO dformjur VALUES ('9240', 'ASS', 'Congrégation');
INSERT INTO dformjur VALUES ('9260', 'ASS', 'Association de droit local (Bas-Rhin, Haut-Rhin et Moselle)');
INSERT INTO dformjur VALUES ('9300', 'FON', 'Fondation');
INSERT INTO dformjur VALUES ('9900', Null, 'Autre personne morale de droit privé');
INSERT INTO dformjur VALUES ('9970', 'GCS', 'Groupement de coopération sanitaire à gestion privée');
INSERT INTO dformjur VALUES ('F001', Null, 'Les copropriétaires');
INSERT INTO dformjur VALUES ('F002', Null, 'Les associés de sci');
INSERT INTO dformjur VALUES ('F003', Null, 'Professionnels très pauvres du foncier');



INSERT INTO ccocac VALUES ('MAG1', 'Boutiques et magasins sur rue (exemples : commerces, restaurants, cafés ou agences bancaires pour une surface principale inférieure à 400 m²)');
INSERT INTO ccocac VALUES ('MAG2', 'Commerces sans accès direct sur la rue (surface principale inférieure à 400 m²)');
INSERT INTO ccocac VALUES ('MAG3', 'Magasins appartenant à un ensemble commercial(surface principale inférieure à 400 m²)');
INSERT INTO ccocac VALUES ('MAG4', 'Magasins de grande surface(surface principale comprise entre 400 et 2 499 m²)');
INSERT INTO ccocac VALUES ('MAG5', 'Magasins de très grande surface (surface principale égale ou supérieure à 2 500 m²)');
INSERT INTO ccocac VALUES ('MAG6', 'Stations - service, stations de lavage et assimilables');
INSERT INTO ccocac VALUES ('MAG7', 'Marchés');
INSERT INTO ccocac VALUES ('BUR1', 'Locaux à usage de bureaux d’agencement ancien');
INSERT INTO ccocac VALUES ('BUR2', 'Locaux à usage de bureaux d’agencement récent');
INSERT INTO ccocac VALUES ('BUR3', 'Locaux assimilables à des bureaux mais présentant des aménagements spécifiques');
INSERT INTO ccocac VALUES ('DEP1', 'Lieux de dépôt à ciel ouvert et terrains à usage commercial ou industriel');
INSERT INTO ccocac VALUES ('DEP2', 'Lieux de dépôt couverts');
INSERT INTO ccocac VALUES ('DEP3', 'Parcs de stationnement à ciel ouvert');
INSERT INTO ccocac VALUES ('DEP4', 'Parcs de stationnement couverts');
INSERT INTO ccocac VALUES ('DEP5', 'Installations spécifiques de stockage');
INSERT INTO ccocac VALUES ('ATE1', 'Ateliers artisanaux');
INSERT INTO ccocac VALUES ('ATE2', 'Locaux utilisés pour une activité de transformation, de manutention ou de maintenance');
INSERT INTO ccocac VALUES ('ATE3', 'Chenils, viviers et autres locaux assimilables');
INSERT INTO ccocac VALUES ('HOT1', 'Hôtels « confort » (4 étoiles et plus, ou confort identique)');
INSERT INTO ccocac VALUES ('HOT2', 'Hôtels « supérieur » (2 ou 3 étoiles, ou confort identique)');
INSERT INTO ccocac VALUES ('HOT3', 'Hôtels « standard » (1 étoile, ou confort identique)');
INSERT INTO ccocac VALUES ('HOT4', 'Foyers d’hébergement, centres d’accueil, auberges de jeunesse');
INSERT INTO ccocac VALUES ('HOT5', 'Hôtels clubs, villages de vacances et résidences hôtelières');
INSERT INTO ccocac VALUES ('SPE1', 'Salles de spectacles, musées et locaux assimilables');
INSERT INTO ccocac VALUES ('SPE2', 'Établissements ou terrains affectés à la pratique d’un sport ou à usage de spectacles sportifs');
INSERT INTO ccocac VALUES ('SPE3', 'Salles de loisirs diverses');
INSERT INTO ccocac VALUES ('SPE4', 'Terrains de camping confortables (3 étoiles et plus, ou confort identique)');
INSERT INTO ccocac VALUES ('SPE5', 'Terrains de camping ordinaires(1 ou 2 étoiles, ou confort identique)');
INSERT INTO ccocac VALUES ('SPE6', 'Établissements de détente et de bien - être');
INSERT INTO ccocac VALUES ('SPE7', 'Centres de loisirs, centres de colonies de vacances, maisons de jeunes');
INSERT INTO ccocac VALUES ('ENS1', 'Écoles et institutions privées exploitées dans un but non lucratif');
INSERT INTO ccocac VALUES ('ENS2', 'Établissements d’enseignement à but lucratif');
INSERT INTO ccocac VALUES ('CLI1', 'Cliniques et Établissements hospitaliers');
INSERT INTO ccocac VALUES ('CLI2', 'Centres médico-sociaux, centres de soins, crèches, halte - garderies');
INSERT INTO ccocac VALUES ('CLI3', 'Maisons de repos, maisons de retraite (médicalisées ou non) et locaux assimilables');
INSERT INTO ccocac VALUES ('CLI4', 'Centres de rééducation, de thalassothérapie, établissements thermaux');
INSERT INTO ccocac VALUES ('IND1', 'Établissements industriels nécessitant un outillage important autres que les carrières et assimilés');
INSERT INTO ccocac VALUES ('IND2', 'carrières et Établissements assimilables');
INSERT INTO ccocac VALUES ('EXC1', 'Locaux ne relevant d’aucune des catégories précédentes par leurs caractéristiques sortant de l’ordinaire');
INSERT INTO ccocac VALUES ('MAG', 'Magasins et lieux de vente');
INSERT INTO ccocac VALUES ('BUR', 'Bureaux et locaux divers assimilables');
INSERT INTO ccocac VALUES ('DEP', 'Lieux de dépôt ou stockage et parcs de stationnement');
INSERT INTO ccocac VALUES ('ATE', 'Ateliers et autres locaux assimilables');
INSERT INTO ccocac VALUES ('HOT', 'Hôtels et locaux assimilables');
INSERT INTO ccocac VALUES ('SPE', 'Etablissements de spectacles, de sports et de loisirs et autres locaux assimilables');
INSERT INTO ccocac VALUES ('ENS', 'Etablissements d''enseignement et locaux assimilables');
INSERT INTO ccocac VALUES ('CLI', 'Cliniques et Établissements du secteur sanitaire et social');
INSERT INTO ccocac VALUES ('IND', 'Établissements industriels n''étant pas évaluées selon la méthode comptable');
INSERT INTO ccocac VALUES ('EXC', 'Autres établissements');



INSERT INTO detent VALUES ('1','bon');
INSERT INTO detent VALUES ('2','assez bon');
INSERT INTO detent VALUES ('3','passable');
INSERT INTO detent VALUES ('4','médiocre');
INSERT INTO detent VALUES ('5','mauvais');

