-- SUPPRESSION DES CONTRAINTES D'INTEGRITEES : DEBUT;

-- suppression clefs primaires;
ALTER TABLE [PREFIXE]geo_tsurf_commune DROP CONSTRAINT geo_tsurf_commune_pk;
ALTER TABLE [PREFIXE]geo_tsurf DROP CONSTRAINT geo_tsurf_pk;
ALTER TABLE [PREFIXE]geo_tline_commune DROP CONSTRAINT geo_tline_commune_pk;
ALTER TABLE [PREFIXE]geo_tline DROP CONSTRAINT geo_tline_pk;
ALTER TABLE [PREFIXE]geo_tpoint_commune DROP CONSTRAINT geo_tpoint_commune_pk;
ALTER TABLE [PREFIXE]geo_tpoint DROP CONSTRAINT geo_tpoint_pk;
ALTER TABLE [PREFIXE]geo_symblim_parcelle DROP CONSTRAINT geo_symblim_parcelle_pk;
ALTER TABLE [PREFIXE]geo_symblim DROP CONSTRAINT geo_symblim_pk;
ALTER TABLE [PREFIXE]geo_croix_parcelle DROP CONSTRAINT geo_croix_parcelle_pk;
ALTER TABLE [PREFIXE]geo_croix DROP CONSTRAINT geo_croix_pk;
ALTER TABLE [PREFIXE]geo_borne_parcelle DROP CONSTRAINT geo_borne_parcelle_pk;
ALTER TABLE [PREFIXE]geo_borne DROP CONSTRAINT geo_borne_pk;
ALTER TABLE [PREFIXE]geo_ptcanv DROP CONSTRAINT geo_ptcanv_pk;
ALTER TABLE [PREFIXE]geo_tronfluv DROP CONSTRAINT geo_tronfluv_pk;
ALTER TABLE [PREFIXE]geo_tronroute DROP CONSTRAINT geo_tronroute_pk;
ALTER TABLE [PREFIXE]geo_zoncommuni DROP CONSTRAINT geo_zoncommuni_pk;
ALTER TABLE [PREFIXE]geo_batiment_parcelle DROP CONSTRAINT geo_batiment_parcelle_pk;
ALTER TABLE [PREFIXE]geo_batiment DROP CONSTRAINT geo_batiment_pk;
ALTER TABLE [PREFIXE]geo_lieudit DROP CONSTRAINT geo_lieudit_pk;
ALTER TABLE [PREFIXE]geo_numvoie_parcelle DROP CONSTRAINT geo_numvoie_parcelle_pk;
ALTER TABLE [PREFIXE]geo_numvoie DROP CONSTRAINT geo_numvoie_pk;
ALTER TABLE [PREFIXE]geo_voiep DROP CONSTRAINT geo_voiep_pk;
ALTER TABLE [PREFIXE]geo_subdfisc_parcelle DROP CONSTRAINT geo_subdfisc_parcelle_pk;
ALTER TABLE [PREFIXE]geo_subdfisc DROP CONSTRAINT geo_subdfisc_pk;
ALTER TABLE [PREFIXE]geo_parcelle DROP CONSTRAINT geo_parcelle_pk;
ALTER TABLE [PREFIXE]geo_subdsect DROP CONSTRAINT geo_subdsect_pk;
ALTER TABLE [PREFIXE]geo_section DROP CONSTRAINT geo_section_pk;
ALTER TABLE [PREFIXE]geo_commune DROP CONSTRAINT geo_commune_pk;
ALTER TABLE [PREFIXE]voie DROP CONSTRAINT voie_pk;
ALTER TABLE [PREFIXE]commune DROP CONSTRAINT commune_pk;
ALTER TABLE [PREFIXE]commune_majic DROP CONSTRAINT commune_majic_pk;
ALTER TABLE [PREFIXE]lotslocaux DROP CONSTRAINT loclocaux_pk;
ALTER TABLE [PREFIXE]lots DROP CONSTRAINT lots_pk;
ALTER TABLE [PREFIXE]parcellecomposante DROP CONSTRAINT parcellecomposante_pk;
ALTER TABLE [PREFIXE]pdl DROP CONSTRAINT pdl_pk;
ALTER TABLE [PREFIXE]comptecommunal DROP CONSTRAINT comptecommunal_pk;
ALTER TABLE [PREFIXE]proprietaire DROP CONSTRAINT proprietaire_pk;
ALTER TABLE [PREFIXE]pevdependances DROP CONSTRAINT pevdependances_pk;
ALTER TABLE [PREFIXE]pevprofessionnelle DROP CONSTRAINT pevprofessionnelle_pk;
ALTER TABLE [PREFIXE]pevprincipale DROP CONSTRAINT pevprincipale_pk;
ALTER TABLE [PREFIXE]pevtaxation DROP CONSTRAINT pevtaxation_pk;
ALTER TABLE [PREFIXE]pevexoneration DROP CONSTRAINT pevexoneration_pk;
ALTER TABLE [PREFIXE]pev DROP CONSTRAINT pev_pk;
ALTER TABLE [PREFIXE]local10 DROP CONSTRAINT local10_pk;
ALTER TABLE [PREFIXE]local00 DROP CONSTRAINT local00_pk;
ALTER TABLE [PREFIXE]suftaxation DROP CONSTRAINT suftaxation_pk;
ALTER TABLE [PREFIXE]sufexoneration DROP CONSTRAINT sufexoneration_pk;
ALTER TABLE [PREFIXE]suf DROP CONSTRAINT suf_pk;
ALTER TABLE [PREFIXE]parcelle DROP CONSTRAINT parcelle_pk;
ALTER TABLE [PREFIXE]geo_unite_fonciere DROP CONSTRAINT geo_unite_fonciere_pk;

--~ -- SUPPRESSION DES CONTRAINTES D'INTEGRITEES : FIN;
