-- PURGE DES DONNEES BRUTES: DEBUT;
TRUNCATE ${PREFIXE}bati;
TRUNCATE ${PREFIXE}topo;
TRUNCATE ${PREFIXE}lloc;
TRUNCATE ${PREFIXE}nbat;
TRUNCATE ${PREFIXE}pdll;
TRUNCATE ${PREFIXE}prop;
-- PURGE DES DONNEES BRUTES: FIN;
