services:
  qgis:
    image: ${QGIS_IMAGE_TAG}
    user: ${UID}:${GID}
    command: /src/.docker/run-tests.sh
    working_dir: /src
    environment:
        HOME: /home/qgis
        QGIS_VERSION: ${QGIS_VERSION}
    volumes:
    - {type: bind, source: "..", target: /src}
    - {type: bind, source: "./qgis_settings.ini", target: /src/tests/qgis_settings.ini}
    profiles:
      - "qgis"

  db:
    image: ${POSTGIS_IMAGE_TAG}
    hostname: db
    environment:
      POSTGRES_DB: "gis"
      POSTGRES_USER: "docker"
      POSTGRES_PASSWORD: "docker"
      POSTGRES_HOST: "db"
    ports:
      - "35432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docker -d gis -q || exit 1"]
      interval: 30s
      timeout: 30s
      start_interval: 2s
      start_period: 10s

  db-runner:
    build:
      context: .
      dockerfile_inline: |
          FROM ${POSTGIS_IMAGE_TAG}
          RUN apt-get -y update && apt-get install -y rename
    user: ${UID}:${GID}
    command: ${DB_COMMAND}
    working_dir: /src/.docker
    entrypoint: /src/.docker/db-runner-entrypoint
    stop_signal: SIGKILL
    volumes:
    - {type: bind, source: "..", target: /src}
    - type: bind
      source: ./pg_service.conf
      target: /etc/postgresql-common/pg_service.conf
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "[ -f /tmp/.db-runner-ok ] || exit 1"]
      start_interval: 2s
      start_period: 10s 
    profiles:
    - schemaspy
    - dbrunner
 
