    <tr>
      <td>$section</td>
      <td>$ndeplan</td>
      <td>$ndevoirie</td>
      <td>$adresse</td>
      <td>$coderivoli</td>
      <td>$bat</td>
      <td>$ent</td>
      <td>$niv</td>
      <td>$ndeporte</td>
      <td>$numeroinvar</td>
      <td>$star</td>
      <td>$meval</td>
      <td>$af</td>
      <td>$natloc</td>
      <td>$cat</td>
      <td>$revenucadastral</td>
      <td>$coll</td>
      <td>$natexo</td>
      <td>$anret</td>
      <td>$andeb</td>
      <td>$fractionrcexo</td>
      <td>$pourcentageexo</td>
      <td>$txom</td>
      <td>$coefreduc</td>
    </tr>
