    <tr>
      <td>{$section}</td>
      <td>{$ndeplan}</td>
      <td>{$ndevoirie}</td>
      <td>{$adresse}</td>
      <td>{$coderivoli}</td>
      <td>{$nparcprim}</td>
      <td>{$fpdp}</td>
      <td>{$star}</td>
      <td>{$suf}</td>
      <td>{$grssgr}</td>
      <td>{$cl}</td>
      <td>{$natcult}</td>
      <td>{$contenance}</td>
      <td>{$revenucadastral}</td>
      <td>{$coll}</td>
      <td>{$natexo}</td>
      <td>{$anret}</td>
      <td>{$fractionrcexo}</td>
      <td>{$pourcentageexo}</td>
      <td>{$tc}</td>
      <td>{$lff}</td>
    </tr>
