# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qadastre_search_form.ui'
#
# Created: Tue Sep 10 18:33:16 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_qadastre_search_form(object):
    def setupUi(self, qadastre_search_form):
        qadastre_search_form.setObjectName(_fromUtf8("qadastre_search_form"))
        qadastre_search_form.resize(355, 625)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.scrollArea_3 = QtGui.QScrollArea(self.dockWidgetContents)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName(_fromUtf8("scrollArea_3"))
        self.scrollAreaWidgetContents_3 = QtGui.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 335, 580))
        self.scrollAreaWidgetContents_3.setObjectName(_fromUtf8("scrollAreaWidgetContents_3"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.groupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents_3)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.inAdresse = QtGui.QLineEdit(self.groupBox)
        self.inAdresse.setObjectName(_fromUtf8("inAdresse"))
        self.verticalLayout_6.addWidget(self.inAdresse)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.btCentrerAdresse = QtGui.QPushButton(self.groupBox)
        self.btCentrerAdresse.setObjectName(_fromUtf8("btCentrerAdresse"))
        self.horizontalLayout.addWidget(self.btCentrerAdresse)
        self.btZoomerAdresse = QtGui.QPushButton(self.groupBox)
        self.btZoomerAdresse.setObjectName(_fromUtf8("btZoomerAdresse"))
        self.horizontalLayout.addWidget(self.btZoomerAdresse)
        self.btSelectionnerAdresse = QtGui.QPushButton(self.groupBox)
        self.btSelectionnerAdresse.setObjectName(_fromUtf8("btSelectionnerAdresse"))
        self.horizontalLayout.addWidget(self.btSelectionnerAdresse)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.verticalLayout_13.addWidget(self.groupBox)
        self.groupBox_5 = QtGui.QGroupBox(self.scrollAreaWidgetContents_3)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_12 = QtGui.QLabel(self.groupBox_5)
        self.label_12.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 0, 0, 1, 1)
        self.inParcelle = QtGui.QLineEdit(self.groupBox_5)
        self.inParcelle.setObjectName(_fromUtf8("inParcelle"))
        self.gridLayout.addWidget(self.inParcelle, 2, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_5)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_5)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.liCommune = QtGui.QComboBox(self.groupBox_5)
        self.liCommune.setObjectName(_fromUtf8("liCommune"))
        self.gridLayout.addWidget(self.liCommune, 0, 1, 1, 1)
        self.liSection = QtGui.QComboBox(self.groupBox_5)
        self.liSection.setObjectName(_fromUtf8("liSection"))
        self.gridLayout.addWidget(self.liSection, 1, 1, 1, 1)
        self.verticalLayout_14.addLayout(self.gridLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.btCentrerLieu = QtGui.QPushButton(self.groupBox_5)
        self.btCentrerLieu.setObjectName(_fromUtf8("btCentrerLieu"))
        self.horizontalLayout_2.addWidget(self.btCentrerLieu)
        self.btZoomerLieu = QtGui.QPushButton(self.groupBox_5)
        self.btZoomerLieu.setObjectName(_fromUtf8("btZoomerLieu"))
        self.horizontalLayout_2.addWidget(self.btZoomerLieu)
        self.btSelectionnerLieu = QtGui.QPushButton(self.groupBox_5)
        self.btSelectionnerLieu.setObjectName(_fromUtf8("btSelectionnerLieu"))
        self.horizontalLayout_2.addWidget(self.btSelectionnerLieu)
        self.verticalLayout_14.addLayout(self.horizontalLayout_2)
        self.verticalLayout_13.addWidget(self.groupBox_5)
        self.groupBox_6 = QtGui.QGroupBox(self.scrollAreaWidgetContents_3)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.inProprietaire = QtGui.QLineEdit(self.groupBox_6)
        self.inProprietaire.setObjectName(_fromUtf8("inProprietaire"))
        self.verticalLayout_2.addWidget(self.inProprietaire)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.btCentrerProprietaire = QtGui.QPushButton(self.groupBox_6)
        self.btCentrerProprietaire.setObjectName(_fromUtf8("btCentrerProprietaire"))
        self.horizontalLayout_3.addWidget(self.btCentrerProprietaire)
        self.btZoomerProprietaire = QtGui.QPushButton(self.groupBox_6)
        self.btZoomerProprietaire.setObjectName(_fromUtf8("btZoomerProprietaire"))
        self.horizontalLayout_3.addWidget(self.btZoomerProprietaire)
        self.btSelectionnerProprietaire = QtGui.QPushButton(self.groupBox_6)
        self.btSelectionnerProprietaire.setObjectName(_fromUtf8("btSelectionnerProprietaire"))
        self.horizontalLayout_3.addWidget(self.btSelectionnerProprietaire)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_13.addWidget(self.groupBox_6)
        self.txtLog = QtGui.QTextEdit(self.scrollAreaWidgetContents_3)
        self.txtLog.setObjectName(_fromUtf8("txtLog"))
        self.verticalLayout_13.addWidget(self.txtLog)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout.addWidget(self.scrollArea_3)
        qadastre_search_form.setWidget(self.dockWidgetContents)

        self.retranslateUi(qadastre_search_form)
        QtCore.QMetaObject.connectSlotsByName(qadastre_search_form)

    def retranslateUi(self, qadastre_search_form):
        qadastre_search_form.setWindowTitle(QtGui.QApplication.translate("qadastre_search_form", "Qadastre - Outils de recherche", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("qadastre_search_form", "Recherche d\'adresse", None, QtGui.QApplication.UnicodeUTF8))
        self.btCentrerAdresse.setText(QtGui.QApplication.translate("qadastre_search_form", "Centrer", None, QtGui.QApplication.UnicodeUTF8))
        self.btZoomerAdresse.setText(QtGui.QApplication.translate("qadastre_search_form", "Zoomer", None, QtGui.QApplication.UnicodeUTF8))
        self.btSelectionnerAdresse.setText(QtGui.QApplication.translate("qadastre_search_form", "Sélectionner", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("qadastre_search_form", "Recherche de lieux", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("qadastre_search_form", "Commune", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("qadastre_search_form", "Parcelle", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("qadastre_search_form", "Section", None, QtGui.QApplication.UnicodeUTF8))
        self.btCentrerLieu.setText(QtGui.QApplication.translate("qadastre_search_form", "Centrer", None, QtGui.QApplication.UnicodeUTF8))
        self.btZoomerLieu.setText(QtGui.QApplication.translate("qadastre_search_form", "Zoomer", None, QtGui.QApplication.UnicodeUTF8))
        self.btSelectionnerLieu.setText(QtGui.QApplication.translate("qadastre_search_form", "Sélectionner", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("qadastre_search_form", "Recherche de propriétaire", None, QtGui.QApplication.UnicodeUTF8))
        self.btCentrerProprietaire.setText(QtGui.QApplication.translate("qadastre_search_form", "Centrer", None, QtGui.QApplication.UnicodeUTF8))
        self.btZoomerProprietaire.setText(QtGui.QApplication.translate("qadastre_search_form", "Zoomer", None, QtGui.QApplication.UnicodeUTF8))
        self.btSelectionnerProprietaire.setText(QtGui.QApplication.translate("qadastre_search_form", "Sélectionner", None, QtGui.QApplication.UnicodeUTF8))
        self.txtLog.setHtml(QtGui.QApplication.translate("qadastre_search_form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))

