name: security

on:
  push:
    tags: 
      - '*'
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  linter:
    runs-on: ubuntu-latest
    name: "Scan"
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
          architecture: x64
          cache: "pip"
          cache-dependency-path: "requirements/security.txt"

      - name: Install Python requirements
        run: pip install -r requirements/security.txt

      - name: Run security scan
        run: |
          bandit --severity-level all -r cadastre
