name: Tests

on:
  push:
    tags: 
      - '*'
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-qgis:
    name: Tests QGIS
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        qgis_version: [
          "3.34",
          "3.40",
          "3.44",
          "nightly-release",
        ]
    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Running tests
        run: make docker-test QGIS_VERSION=${{ matrix.qgis_version }}
